(dynamic-load "gdbm.so")
(define db (gdbm-open "definitions.db"))
(gdbm-store-replace db "taylor" "American physicist. He shared a 1993 Nobel Prize for the discovery of a new type of pulsar. A city of southeast Michigan, a suburb of Detroit. Population: 70,811. American choreographer whose avant-garde work includes Three Epitaphs (1956) and Orbs (1966). American jazz pianist and composer who was a leader of the free jazz movement of the 1960s, which emphasized unrestrained, emotional play and group improvisation. British playwright whose works include Our American Cousin (1858). American inventor, engineer, and efficiency expert noted for his innovations in industrial engineering and management.")
(gdbm-store-replace db "plesent" "no definitions found.")
(gdbm-store-replace db "biik" "no definitions found.")
(gdbm-store-replace db "comeupannce." "no definitions found.")
(gdbm-store-replace db "clerical" "Of or relating to clerks or office workers or their work. Of, relating to, or characteristic of the clergy. Advocating clericalism. A member of the clergy. clericals Garments worn by the clergy. An advocate of clericalism.")
(gdbm-store-replace db "aping" "Any of various large, tailless Old World primates of the family Pongidae, including the chimpanzee, gorilla, gibbon, and orangutan. A mimic or imitator. Informal. A clumsy or boorish person. To mimic slavishly but often with an absurd result. See Synonyms at imitate. To become wildly excited or enthusiastic: went ape at the party; goes ape over Thai cuisine. ")
(gdbm-store-replace db "mete" "To distribute by or as if by measure; allot: mete out justice.  Archaic. To measure. A boundary line; a limit.")
(gdbm-store-replace db "dotted" "A tiny round mark made by or as if by a pointed instrument; a spot. A tiny amount. In Morse and similar codes, the short sound or signal used in combination with the dash and silent intervals to represent letters, numbers, or punctuation. Mathematics. A decimal point. Music. A mark after a note indicating an increase in time value by half. Computer Science. A period, as used as in URLs and e-mail addresses, to separate strings of words, as in www.hmco.com.")
(gdbm-store-replace db "proselytize" "To induce someone to convert to one's own religious faith. To induce someone to join one's own political party or to espouse one's doctrine. To convert (a person) from one belief, doctrine, cause, or faith to another.")
(gdbm-store-replace db "deplore" "To express sorrow or grief over. To regret; bemoan.")
(gdbm-store-replace db "tarn" "A small mountain lake, especially one formed by glaciers. A river, about 378 km (235 mi) long, of southern France flowing generally west and southwest to the Garonne River.")
(gdbm-store-replace db "role" "also rôle A character or part played by a performer. The characteristic and expected social behavior of an individual. A function or position. See Synonyms at function. Linguistics. The function of a word or construction, as in a sentence.")
(gdbm-store-replace db "trifeca" "no definitions found.")
(gdbm-store-replace db "cock" "An adult male chicken; a rooster. A weathervane shaped like a rooster; a weathercock. A leader or chief. A faucet or valve by which the flow of a liquid or gas can be regulated.  The hammer of a firearm. A tilting or jaunty turn upward: the cock of a hat. ")
(gdbm-store-replace db "angry" "Feeling or showing anger; incensed or enraged: angry at a rude neighbor; angry with a salesclerk.  Indicative of or resulting from anger: an angry silence.  Having a menacing aspect; threatening: angry clouds on the horizon.  Chiefly New England   Midland U.S. Inflamed and painful: an angry sore. ")
(gdbm-store-replace db "sinture" "no definitions found.")
(gdbm-store-replace db "rollick" "To behave or move in a carefree, frolicsome manner; romp.")
(gdbm-store-replace db "majority" "The greater number or part; a number more than half of the total. The amount by which the greater number of votes cast, as in an election, exceeds the total number of remaining votes. The political party, group, or faction having the most power by virtue of its larger representation or electoral strength. Law. The status of having reached full legal age, with attendant rights and responsibilities. The military rank, commission, or office of a major. Obsolete. The fact or state of being greater; superiority.")
(gdbm-store-replace db "lazy" "Resistant to work or exertion; disposed to idleness. Slow-moving; sluggish: a lazy river.  Conducive to idleness or indolence: a lazy summer day.  Depicted as reclining or lying on its side. Used of a brand on livestock. Mark.")
(gdbm-store-replace db "doted" "To show excessive fondness or love: parents who dote on their only child. ")
(gdbm-store-replace db "sinchure" "no definitions found.")
(gdbm-store-replace db "nechanged" "no definitions found.")
(gdbm-store-replace db "piiza" "no definitions found.")
(gdbm-store-replace db "croquembouche" "no definitions found.")
(gdbm-store-replace db "yes" "It is so; as you say or ask. Used to express affirmation, agreement, positive confirmation, or consent. An affirmative or consenting reply. An affirmative vote or voter. To give an affirmative reply to. Used to express great satisfaction, approval, or happiness.")
(gdbm-store-replace db "groove" "A long narrow furrow or channel. The spiral track cut into a phonograph record for the stylus to follow. Slang. A settled routine: got into the groove of a nine-to-five job.  Slang. A situation or an activity that one enjoys or to which one is especially well suited: found his groove playing bass in a trio.  Slang. A very pleasurable experience. To cut a groove or grooves in. Baseball. To throw (a pitch) over the middle of home plate, where it is likely to be hit. To take great pleasure or satisfaction; enjoy oneself: just sitting around, grooving on the music.  To react or interact harmoniously. Performing exceptionally well.")
(gdbm-store-replace db "bew" "no definitions found.")
(gdbm-store-replace db "gaffe" "A public place of entertainment, especially a cheap or disreputable music hall or theater. Slang. A house, building, or apartment, especially where one resides. A large iron hook attached to a pole or handle and used to land large fish. Nautical. A spar attached to the mast and used to extend the upper edge of a fore-and-aft sail.  A sharp metal spur or spike fastened to the leg of a gamecock. Slang. A trick or gimmick, especially one used in a swindle or to rig a game.")
(gdbm-store-replace db "cinch" "A girth for a pack or saddle. A firm grip. Something easy to accomplish. See Synonyms at breeze1. A sure thing; a certainty. To put a saddle girth on. To get a tight grip on.")
(gdbm-store-replace db "stip clubs" "no definitions found.")
(gdbm-store-replace db "lieave" "no definitions found.")
(gdbm-store-replace db "cinche" "no definitions found.")
(gdbm-store-replace db "furfuraceous" "Made of or covered with scaly particles, such as dandruff. Relating to or resembling bran.")
(gdbm-store-replace db "exigency" "The state or quality of requiring much effort or immediate action. A pressing or urgent situation. See Synonyms at crisis. Urgent requirements; pressing needs. Often used in the plural.")
(gdbm-store-replace db "triangle" "The plane figure formed by connecting three points not in a straight line by straight line segments; a three-sided polygon. Any of various flat, three-sided drawing and drafting guides, used especially to draw straight lines at specific angles. Music. A percussion instrument consisting of a piece of metal in the shape of a triangle open at one angle. A relationship involving three people, especially a ménage à trois.")
(gdbm-store-replace db "collegial" "Of, relating to, characterized by, or likened to college life; collegiate: collegial rituals like homecoming. ")
(gdbm-store-replace db "pale" "A stake or pointed stick; a picket. A fence enclosing an area. The area enclosed by a fence or boundary.  A region or district lying within an imposed boundary or constituting a separate jurisdiction. Heraldry. A wide vertical band in the center of an escutcheon. To enclose with pales; fence in.")
(gdbm-store-replace db "hook" "A curved or sharply bent device, usually of metal, used to catch, drag, suspend, or fasten something else. Something shaped like a hook, especially: A curved or barbed plant or animal part.  A sharp bend or curve, as in a river. A means of catching or ensnaring; a trap. Slang. A means of attracting interest or attention; an enticement: a sales hook.  Sports. A short swinging blow in boxing delivered with a crooked arm.")
(gdbm-store-replace db "insolence" "The quality or condition of being insolent. An instance of insolent behavior, treatment, or speech.")
(gdbm-store-replace db "annoying" "To cause slight irritation to (another) by troublesome, often repeated acts. To harass or disturb by repeated attacks. To be annoying. Causing vexation or irritation; troublesome: an annoying cough. ")
(gdbm-store-replace db "flit" "To move about rapidly and nimbly. To move quickly from one condition or location to another. A fluttering or darting movement. Informal. An empty-headed, silly, often erratic person.")
(gdbm-store-replace db "lucid" "Easily understood; intelligible. Mentally sound; sane or rational. Translucent or transparent. See Synonyms at clear.")
(gdbm-store-replace db "plan" "Variant of plano-. A scheme, program, or method worked out beforehand for the accomplishment of an objective: a plan of attack.  A proposed or tentative project or course of action: had no plans for the evening.  A systematic arrangement of elements or important parts; a configuration or outline: a seating plan; the plan of a story.  A drawing or diagram made to scale showing the structure or arrangement of something. In perspective rendering, one of several imaginary planes perpendicular to the line of vision between the viewer and the object being depicted.")
(gdbm-store-replace db "prepair" "no definitions found.")
(gdbm-store-replace db "probly" "no definitions found.")
(gdbm-store-replace db "idiot" "A foolish or stupid person.")
(gdbm-store-replace db "fungible" "Law. Returnable or negotiable in kind or by substitution, as a quantity of grain for an equal amount of the same kind of grain. Interchangeable. Something that is exchangeable or substitutable. Often used in the plural.")
(gdbm-store-replace db "ahold" "Hold; grip:  I knew I could make it all right if I got... back to the hotel and got ahold of that bottle of brandy  (Jimmy Breslin).")
(gdbm-store-replace db "stringer" "One that strings: a stringer of beads.  Architecture. A long heavy horizontal timber used as a support or connector. A horizontal timber used to support upright posts. Sports. A member of a specified string or squad on a team. Often used in combination: a first-stringer; a second-stringer.  A part-time or freelance correspondent for the news media.")
(gdbm-store-replace db "fiction" "An imaginative creation or a pretense that does not represent actuality but has been invented. A lie.  A literary work whose content is produced by the imagination and is not necessarily based on fact. Law. Something untrue that is intentionally represented as true by the narrator.")
(gdbm-store-replace db "hebetude" "Dullness of mind; mental lethargy.")
(gdbm-store-replace db "honkers" "no definitions found.")
(gdbm-store-replace db "prepend" "no definitions found.")
(gdbm-store-replace db "lethe" "Lethe Greek Mythology. The river of forgetfulness, one of the five rivers in Hades. A condition of forgetfulness; oblivion.")
(gdbm-store-replace db "fulgid" "no definitions found.")
(gdbm-store-replace db "springer" "A springer spaniel. Western U.S. A cow about to give birth. Architecture. The bottom stone of an arch resting on the impost.")
(gdbm-store-replace db "vanilla" "The seedpod of this plant. Also called vanilla bean. A flavoring extract prepared from the cured seedpods of this plant or produced synthetically. Flavored with vanilla: vanilla pudding. ")
(gdbm-store-replace db "petulant" "Unreasonably irritable or ill-tempered; peevish. Contemptuous in speech or behavior.")
(gdbm-store-replace db "stricture" "A restraint, limit, or restriction. An adverse remark or criticism; censure. Pathology. An abnormal narrowing of a duct or passage.")
(gdbm-store-replace db "halcyon" "A kingfisher, especially one of the genus Halcyon. A fabled bird, identified with the kingfisher, that was supposed to have had the power to calm the wind and the waves while it nested on the sea during the winter solstice. Calm and peaceful; tranquil. Prosperous; golden: halcyon years. ")
(gdbm-store-replace db "cinture" "no definitions found.")
(gdbm-store-replace db "nooner" "no definitions found.")
(gdbm-store-replace db "hyper" "Having a very excitable or nervous temperament; high-strung. Emotionally stimulated or overexcited. Over; above; beyond: hypercharge.  Excessive; excessively: hypercritical.  Existing in more than three dimensions: hyperspace.  Linked or arranged nonsequentially: hypertext. ")
(gdbm-store-replace db "esoteric" "Intended for or understood by only a particular group: an esoteric cult. See Synonyms at mysterious.  Confined to a small group: esoteric interests. ")
(gdbm-store-replace db "imputation" "The act of imputing or ascribing; attribution. Something imputed, ascribed, or attributed.")
(gdbm-store-replace db "wee wee" "no definitions found.")
(gdbm-store-replace db "hence" "For this reason; therefore: handmade and hence expensive.  From this time; from now: A year hence it will be forgotten.  From this place; away from here: Get you hence! ")
(gdbm-store-replace db "gestalt" "no definitions found.")
(gdbm-store-replace db "monseigneur" "Used as an honorific in French-speaking areas, especially as accorded to princes and prelates.")
(gdbm-store-replace db "cudgel" "A short heavy stick; a club.")
(gdbm-store-replace db "spieler" "A lengthy or extravagant speech or argument usually intended to persuade. To talk or say (something) at length or extravagantly.")
(gdbm-store-replace db "haiku" "A poem written in this form.")
(gdbm-store-replace db "pinion" "The wing of a bird. The outer rear edge of the wing of a bird, containing the primary feathers. A primary feather of a bird.  To remove or bind the wing feathers of (a bird) to prevent flight.  To restrain or immobilize (a person) by binding the arms. To bind fast or hold down; shackle.")
(gdbm-store-replace db "cinchure" "no definitions found.")
(gdbm-store-replace db "antithetical" "Of, relating to, or marked by antithesis. Being in diametrical opposition. See Synonyms at opposite.")
(gdbm-store-replace db "pier" "A platform extending from a shore over water and supported by piles or pillars, used to secure, protect, and provide access to ships or boats. A supporting structure at the junction of connecting spans of a bridge. Architecture. Any of various vertical supporting structures, especially: A pillar, generally rectangular in cross section, supporting an arch or roof.")
(gdbm-store-replace db "torpidity" "The quality or state of being torpid. See Synonyms at lethargy.")
(gdbm-store-replace db "alb" "Ecclesiastical. A long white linen robe with tapered sleeves worn by a priest at Mass. Albania. Albanian. Of or relating to Albania or its people, language, or culture. A native or inhabitant of Albania. The Indo-European language of the Albanians.")
(gdbm-store-replace db "scat" "Jazz singing in which improvised, meaningless syllables are sung to a melody. To sing scat. Excrement, especially of an animal; dung. To go away hastily; leave at once.")
(gdbm-store-replace db "curtat" "no definitions found.")
(gdbm-store-replace db "bombas" "no definitions found.")
(gdbm-store-replace db "befog" "To cover or obscure with or as if with fog. To cause confusion in; muddle.")
(gdbm-store-replace db "sphincter" "A ringlike muscle that normally maintains constriction of a body passage or orifice and that relaxes as required by normal physiological functioning.")
(gdbm-store-replace db "brume" "Fog or mist.")
(gdbm-store-replace db "bistro" "A small bar, tavern, or nightclub. A small, informal restaurant serving wine.")
(gdbm-store-replace db "faig" "no definitions found.")
(gdbm-store-replace db "augur" "One of a group of ancient Roman religious officials who foretold events by observing and interpreting signs and omens. A seer or prophet; a soothsayer. To predict, especially from signs or omens; foretell. See Synonyms at foretell. To serve as an omen of; betoken: trends that augur change in society.  To make predictions from signs or omens. To be a sign or omen: A smooth dress rehearsal augured well for the play. ")
(gdbm-store-replace db "cassock" "An ankle-length garment with a close-fitting waist and sleeves, worn by the clergy and others assisting in church services.")
(gdbm-store-replace db "anthropology" "The scientific study of the origin, the behavior, and the physical, social, and cultural development of humans.")
(gdbm-store-replace db "snoogins" "bennid or the one who?")
(gdbm-store-replace db "sandwitches" "no definitions found.")
(gdbm-store-replace db "hooker" "One that hooks. Slang. A prostitute. A single-masted fishing smack used off the coast of Ireland. An old worn-out or clumsy ship. A drink of undiluted hard liquor: a hooker of whiskey.  American Union army officer who was defeated by Robert E. Lee at Chancellorsville (1863). English writer and theologian. His Laws of Ecclesiastical Polity (1594) was central to the formation of Anglican theology. English-born American colonizer and cleric who founded Hartford, Connecticut (1636).")
(gdbm-store-replace db "bioluminescent" "Emission of visible light by living organisms such as the firefly and various fish, fungi, and bacteria.")
(gdbm-store-replace db "dossier" "A collection of papers giving detailed information about a particular person or subject.")
(gdbm-store-replace db "hink" "no definitions found.")
(gdbm-store-replace db "synod" "A council or an assembly of church officials or churches; an ecclesiastical council. A council or an assembly.")
(gdbm-store-replace db "yabbos" "no definitions found.")
(gdbm-store-replace db "bombass" "no definitions found.")
(gdbm-store-replace db "comeupannce" "no definitions found.")
(gdbm-store-replace db "damn" "To pronounce an adverse judgment upon. See Synonyms at condemn. To bring about the failure of; ruin. To condemn as harmful, illegal, or immoral: a cleric who damned gambling and strong drink.  To condemn to everlasting punishment or a similar fate; doom. To swear at. To swear; curse.")
(gdbm-store-replace db "traduce" "no definitions found.")
(gdbm-store-replace db "01woukld" "no definitions found.")
(gdbm-store-replace db "efficacious" "Producing or capable of producing a desired effect. See Synonyms at effective.")
(gdbm-store-replace db "terminus" "An end point on a transportation line or the town in which it is located.  A boundary or border.")
(gdbm-store-replace db "scatalogical" "no definitions found.")
(gdbm-store-replace db "blaster" "A very strong gust of wind or air. A forcible stream of air, gas, or steam from an opening, especially one in a blast furnace to aid combustion.  A sudden loud sound, especially one produced by a stream of forced air: a piercing blast from the steam whistle.  A violent explosion, as of dynamite or a bomb. Botany. Any of several plant diseases of diverse causes, resulting in sudden death of buds, flowers, foliage, or young fruits. A destructive or damaging influence.")
(gdbm-store-replace db "uber" "no definitions found.")
(gdbm-store-replace db "exploded" "To release mechanical, chemical, or nuclear energy by the sudden production of gases in a confined space: The bomb exploded.  To burst violently as a result of internal pressure. To shatter with a loud noise: The vase exploded into tiny pieces when it hit the floor.  To make an emotional outburst: My neighbor exploded in rage at the trespassers.  To increase suddenly, sharply, and without control: The population level in this area has exploded during the past 12 years.  To change state or appearance suddenly: Over the weekend the trees exploded with color. ")
(gdbm-store-replace db "amorial" "no definitions found.")
(gdbm-store-replace db "spelled" "A short, indefinite period of time. Informal. A period of weather of a particular kind: a dry spell.  One's turn at work. Australian. A period of rest. Informal. A period of physical or mental disorder or distress: a dizzy spell.  Informal. A short distance.")
(gdbm-store-replace db "adjuration" "An earnest, solemn appeal.")
(gdbm-store-replace db "restorewd" "no definitions found.")
(gdbm-store-replace db "benignant" "Favorable; beneficial. Kind and gracious.")
(gdbm-store-replace db "pendant" "Hanging down; dangling; suspended. Projecting; overhanging. Awaiting settlement; pending. Variant of pendent1. Something suspended from something else, especially an ornament or piece of jewelry attached to a necklace or bracelet. A hanging lamp or chandelier.")
(gdbm-store-replace db "because" "For the reason that; since.")
(gdbm-store-replace db "ragchewing" "no definitions found.")
(gdbm-store-replace db "bioluminescient" "no definitions found.")
(gdbm-store-replace db "avowed" "To state positively.")
(gdbm-store-replace db "ereet" "no definitions found.")
(gdbm-store-replace db "empyrean" "The highest reaches of heaven, believed by the ancients to be a realm of pure fire or light. The sky. Of or relating to the empyrean of ancient belief.")
(gdbm-store-replace db "abjure" "To renounce under oath; forswear. To recant solemnly; repudiate: abjure one's beliefs. ")
(gdbm-store-replace db "hewn" "A past participle of hew. To make or shape with or as if with an ax: hew a path through the underbrush.  To cut down with an ax; fell: hew an oak.  To strike or cut; cleave. To cut something by repeated blows, as of an ax. To adhere or conform strictly; hold: hew to the line. ")
(gdbm-store-replace db "lathe" "A machine for shaping a piece of material, such as wood or metal, by rotating it rapidly along its axis while pressing against a fixed cutting or abrading tool. To cut or shape on a lathe.")
(gdbm-store-replace db "barricade" "A structure set up across a route of access to obstruct the passage of an enemy. Something that serves as an obstacle; a barrier. See Synonyms at bulwark. To close off or block with a barricade. To keep in or out by means of a barricade.")
(gdbm-store-replace db "removeed" "no definitions found.")
(gdbm-store-replace db "one" "Being a single entity, unit, object, or living being. Characterized by unity; undivided: They spoke with one voice.  Of the same kind or quality: two animals of one species.  Being a single member or element of a group, category, or kind: I'm just one player on the team.  Being a single thing in contrast with or relation to another or others of its kind: One day is just like the next.  Occurring or existing as something indefinite, as in time or position: He will come one day.  Occurring or existing as something particular but unspecified, as in time past: late one evening.  Informal. Used as an intensive: That is one fine dog.  Being the only individual of a specified or implied kind: the one person I could marry; the one horse that can win this race.  The cardinal number, represented by the symbol 1, designating the first such unit in a series. A single person or thing; a unit: This is the one I like best.  A one-dollar bill. An indefinitely specified individual: She visited one of her cousins.  In accord or unity. A ketone: acetone.  A chemical compound containing oxygen, especially in a carbonyl group: lactone. ")
(gdbm-store-replace db "voices" "The sound produced by the vocal organs of a vertebrate, especially a human. A specified quality, condition, or pitch of vocal sound: a hoarse voice; the child's piping voice.  Linguistics. Expiration of air through vibrating vocal cords, used in the production of vowels and voiced consonants. A sound resembling or reminiscent of vocal utterance: the murmuring voice of the forest.  Music. Musical sound produced by vibration of the human vocal cords and resonated within the throat and head cavities.  Expression; utterance: gave voice to their feelings at the meeting. ")
(gdbm-store-replace db "equitable" "Marked by or having equity; just and impartial. See Synonyms at fair1.")
(gdbm-store-replace db "railroad" "A road composed of parallel steel rails supported by ties and providing a track for locomotive-drawn trains or other wheeled vehicles. A system of railroad track, together with the land, stations, rolling stock, and other related property under one management. To transport by railroad. To supply (an area) with railroads. To work for a railroad company.")
(gdbm-store-replace db "logic" "The study of the principles of reasoning, especially of the structure of propositions as distinguished from their content and of method and validity in deductive reasoning.  A system of reasoning: Aristotle's logic.  Valid reasoning: Your paper lacks the logic to prove your thesis.  Computer Science. The nonarithmetic operations performed by a computer, such as sorting, comparing, and matching, that involve yes-no decisions.")
(gdbm-store-replace db "epistemology" "The branch of philosophy that studies the nature of knowledge, its presuppositions and foundations, and its extent and validity.")
(gdbm-store-replace db "rounder" "Linguistics. Formed or articulated with the lips in a rounded shape: a round vowel.  Whole or complete; full: a round dozen.  Mathematics. Expressed or designated as a whole number or integer; not fractional. Large; considerable: a round sum of money.  Brought to satisfactory conclusion or completion; finished.  Outspoken; blunt: a round scolding. ")
(gdbm-store-replace db "impregnable" "Impossible to capture or enter by force: an impregnable fortress.  Difficult or impossible to attack, challenge, or refute with success: an impregnable argument.  Capable of being impregnated.")
(gdbm-store-replace db "tenue" "no definitions found.")
(gdbm-store-replace db "aldermanic" "A member of the municipal legislative body in a town or city in many jurisdictions. A member of the higher branch of the municipal or borough council in England and Ireland before 1974.  A noble of high rank or authority in Anglo-Saxon England.")
(gdbm-store-replace db "boob" "A stupid or foolish person; a dolt. A woman's breast.")
(gdbm-store-replace db "foist" "To impose (something or someone unwanted) upon another by coercion or trickery: They had extra work foisted on them because they couldn't say no to the boss.  To insert fraudulently or deceitfully: foisted unfair provisions into the contract. ")
(gdbm-store-replace db "pag" "no definitions found.")
(gdbm-store-replace db "shelbes" "no definitions found.")
(gdbm-store-replace db "apple" "A deciduous Eurasian tree (Malus pumila) having alternate simple leaves and white or pink flowers.  Any of several other plants, especially those with fruits suggestive of the apple, such as the crab apple or custard apple. One that is treasured: Her grandson is the apple of her eye. ")
(gdbm-store-replace db "insolince" "no definitions found.")
(gdbm-store-replace db "renunciation" "The act or an instance of renouncing: the renunciation of all earthly pleasures.  A declaration in which something is renounced.")
(gdbm-store-replace db "bombastic" "Grandiloquent, pompous speech or writing.")
(gdbm-store-replace db "hebetud" "no definitions found.")
(gdbm-store-replace db "compeer" "A person of equal status or rank; a peer. A comrade, companion, or associate.")
(gdbm-store-replace db "torrid" "Parched with the heat of the sun; intensely hot. Scorching; burning: the torrid noonday sun.  Passionate; ardent: a torrid love scene.  Hurried; rapid: set a torrid pace; torrid economic growth. ")
(gdbm-store-replace db "harbinger" "One that indicates or foreshadows what is to come; a forerunner. To signal the approach of; presage.")
(gdbm-store-replace db "angery" "no definitions found.")
(gdbm-store-replace db "oxycodone" "no definitions found.")
(gdbm-store-replace db "insolent" "Presumptuous and insulting in manner or speech; arrogant. Audaciously rude or disrespectful; impertinent.")
(gdbm-store-replace db "spelt" "A short, indefinite period of time. Informal. A period of weather of a particular kind: a dry spell.  One's turn at work. Australian. A period of rest. Informal. A period of physical or mental disorder or distress: a dizzy spell.  Informal. A short distance.")
(gdbm-store-replace db "bazongas" "no definitions found.")
(gdbm-store-replace db "ahould" "a more clever way of spelling 'should'.")
(gdbm-store-replace db "sanguine" "Of the color of blood; red. Archaic. Having blood as the dominant humor in terms of medieval physiology. Cheerfully confident; optimistic.")
(gdbm-store-replace db "traduced" "no definitions found.")
(gdbm-store-replace db "ruminating" "To turn a matter over and over in the mind. To chew cud. To reflect on over and over again.")
(gdbm-store-replace db "elision" "Omission of a final or initial sound in pronunciation. The act or an instance of omitting something.")
(gdbm-store-replace db "becuase" "no definitions found.")
(gdbm-store-replace db "brade" "no definitions found.")
(gdbm-store-replace db "jumbly" "no definitions found.")
(gdbm-store-replace db "cunt" "The female genital organs. Sexual intercourse with a woman.  Offensive. Used as a disparaging term for a woman.")
(gdbm-store-replace db "philter" "A love potion. A magic potion or charm.")
(gdbm-store-replace db "ben" "The inner room or parlor of a house with two rooms. Inside; within. Within.")
(gdbm-store-replace db "pedagogic" "Of, relating to, or characteristic of pedagogy. Characterized by pedantic formality: a haughty, pedagogic manner. ")
(gdbm-store-replace db "cumupannce" "no definitions found.")
(gdbm-store-replace db "rhythmic" "Of, relating to, or having rhythm; recurring with measured regularity.")
(gdbm-store-replace db "somolence" "no definitions found.")
(gdbm-store-replace db "magnate" "A powerful or influential person, especially in business or industry: an oil magnate. ")
(gdbm-store-replace db "cinchur" "no definitions found.")
(gdbm-store-replace db "pat" "Trite or glib; superficially complete or satisfactory: A pat answer is not going to satisfy an inquisitive audience.  Timely or opportune. Games. Being a poker hand that is strong enough to make drawing cards unlikely to improve it. Completely, exactly, or perfectly: They've got the system down pat. He has the lesson pat.   To tap gently with the open hand or with something flat. To mold by tapping gently with the hands or a flat implement.")
(gdbm-store-replace db "limpid" "Characterized by transparent clearness; pellucid. See Synonyms at clear. Easily intelligible; clear: writes in a limpid style.  Calm and untroubled; serene.")
(gdbm-store-replace db "ascribe" "To assign as a quality or characteristic: was quick to ascribe jealousy to her critics. ")
(gdbm-store-replace db "arrested" "To stop; check: a brake that automatically arrests motion; arrested the growth of the tumor.  To seize and hold under the authority of law. To capture and hold briefly (the attention, for example); engage. To undergo cardiac arrest: The patient arrested en route to the hospital.  The act of detaining in legal custody: the arrest of a criminal suspect.  A device for stopping motion, especially of a moving part.")
(gdbm-store-replace db "pharmacopoeia" "A book containing an official list of medicinal drugs together with articles on their preparation and use. A collection or stock of drugs.")
(gdbm-store-replace db "oging" "no definitions found.")
(gdbm-store-replace db "meme" "A unit of cultural information, such as a cultural practice or idea, that is transmitted verbally or by repeated action from one mind to another.")
(gdbm-store-replace db "croupier" "An attendant at a gaming table who collects and pays bets.")
(gdbm-store-replace db "fedora" "A soft felt hat with a fairly low crown creased lengthwise and a brim that can be turned up or down.")
(gdbm-store-replace db "lenity" "The condition or quality of being lenient; leniency. See Synonyms at mercy.")
(gdbm-store-replace db "connivance" "The act of conniving. Law. Knowledge of and tacit consent to the commission of an illegal act by another.")
(gdbm-store-replace db "prattle" "To talk or chatter idly or meaninglessly; babble or prate. To utter or express by chattering foolishly or babbling. Idle or meaningless chatter; babble. A sound suggestive of such chattering; a babbling noise.")
(gdbm-store-replace db "pistemology" "no definitions found.")
(gdbm-store-replace db "interdict" "To prohibit or place under an ecclesiastical or legal sanction. To forbid or debar, especially authoritatively. See Synonyms at forbid.  To cut or destroy (a line of communication) by firepower so as to halt an enemy's advance. Law. A prohibition by court order. Roman Catholic Church. An ecclesiastical censure that excludes a person or district from participation in most sacraments and from Christian burial.")
(gdbm-store-replace db "definition" "A statement conveying fundamental character. The act or process of stating a precise meaning or significance; formulation of a meaning.  The act of making clear and distinct: a definition of one's intentions.  The clarity of detail in an optically produced image, such as a photograph, effected by a combination of resolution and contrast.")
(gdbm-store-replace db "nipper" "A tool, such as pliers or pincers, used for squeezing or nipping. Often used in the plural. A pincerlike part, such as the large claw of a crustacean. Chiefly British. A small boy.")
(gdbm-store-replace db "poop" "To quit because of exhaustion: poop out of a race.  To decide not to participate, especially at the last moment. An enclosed superstructure at the stern of a ship. A poop deck. To break over the stern of (a ship). To take (a wave) over the stern.")
(gdbm-store-replace db "pedagogy" "The art or profession of teaching. Preparatory training or instruction.")
(gdbm-store-replace db "gambol" "A playful skipping or frolicking about.")
(gdbm-store-replace db "lexicon" "A dictionary. A stock of terms used in a particular profession, subject, or style; a vocabulary: the lexicon of surrealist art.  Linguistics. The morphemes of a language considered as a group.")
(gdbm-store-replace db "castigate" "To criticize severely.")
(gdbm-store-replace db "insolance" "no definitions found.")
(gdbm-store-replace db "lugubrious" "Mournful, dismal, or gloomy, especially to an exaggerated or ludicrous degree.")
(gdbm-store-replace db "clit" "no definitions found.")
(gdbm-store-replace db "ninny" "A fool; a simpleton.")
(gdbm-store-replace db "word" "Something said; an utterance, remark, or comment: May I say a word about that?  Computer Science. A set of bits constituting the smallest unit of addressable memory. words Discourse or talk; speech: Actions speak louder than words.  words Music. The text of a vocal composition; lyrics. An assurance or promise; sworn intention: She has kept her word.  A command or direction; an order: gave the word to retreat. ")
(gdbm-store-replace db "metaphysics" "Metaphysics. An underlying philosophical or theoretical principle: a belief in luck, the metaphysic of the gambler.  (used with a pl. verb) The theoretical or first principles of a particular discipline: the metaphysics of law.  (used with a sing. verb) A priori speculation upon questions that are unanswerable to scientific observation, analysis, or experiment. (used with a sing. verb) Excessively subtle or recondite reasoning.")
(gdbm-store-replace db "acerbic" "Sour or bitter tasting; acid. See Synonyms at bitter.")
(gdbm-store-replace db "sincerly" "no definitions found.")
(gdbm-store-replace db "bric-a-brac" "Small, usually ornamental objects valued for their antiquity, rarity, originality, or sentimental associations.")
(gdbm-store-replace db "corrigible" "Capable of being corrected, reformed, or improved.")
(gdbm-store-replace db "comupannce" "no definitions found.")
(gdbm-store-replace db "necropiliac" "no definitions found.")
(gdbm-store-replace db "rule" "Governing power or its possession or use; authority. A generalized statement that describes what is true in most or all cases: In this office, hard work is the rule, not the exception.  Mathematics. A standard method or procedure for solving a class of problems. Law. A court order limited in application to a specific case. See ruler. Printing. A thin metal strip of various widths and designs, used to print borders or lines, as between columns.")
(gdbm-store-replace db "comber" "One, such as a machine or a worker, that combs something, such as wool. A long wave that has reached its peak or broken into foam; a breaker.")
(gdbm-store-replace db "canonical" "Of, relating to, or required by canon law. Of or appearing in the biblical canon. Conforming to orthodox or well-established rules or patterns, as of procedure. Of or belonging to a cathedral chapter. Of or relating to a literary canon: a canonical writer like Keats.  Music. Having the form of a canon.")
(gdbm-store-replace db "avaricious" "Immoderately desirous of wealth or gain; greedy.")
(gdbm-store-replace db "wnat" "no definitions found.")
(gdbm-store-replace db "boobies" "A person regarded as stupid. Any of several tropical sea birds of the genus Sula, resembling and related to the gannets. A woman's breast.")
(gdbm-store-replace db "innuence" "no definitions found.")
(gdbm-store-replace db "appurtenance" "Something added to another, more important thing; an appendage. See Synonyms at appendage. appurtenances Equipment, such as clothing, tools, or instruments, used for a specific purpose or task; gear. Law. A right, privilege, or property that is considered incident to the principal property for purposes such as passage of title, conveyance, or inheritance.")
(gdbm-store-replace db "mellowness" " Soft, sweet, juicy, and full-flavored because of ripeness: a mellow fruit.  Rich and soft in quality: a mellow sound; a mellow wine.  Having the gentleness, wisdom, or tolerance often characteristic of maturity. Relaxed and unhurried; easygoing: a mellow friend; a mellow conversation.  Slang. Slightly and pleasantly intoxicated. Moist, rich, soft, and loamy. Used of soil.")
(gdbm-store-replace db "mores" "The accepted traditional customs and usages of a particular social group. Moral attitudes. Manners; ways.")
(gdbm-store-replace db "leathe" "no definitions found.")
(gdbm-store-replace db "saz" "no definitions found.")
(gdbm-store-replace db "sass" "Impertinent, disrespectful speech; back talk. To talk impudently to.")
(gdbm-store-replace db "jugs" "A large, often rounded vessel of earthenware, glass, or metal with a small mouth, a handle, and usually a stopper or cap. A small pitcher. Slang. A jail. jugs Vulgar Slang. A woman's breasts. To stew (a hare, for example) in an earthenware jug or jar. Slang. To put into jail.")
(gdbm-store-replace db "curtate" "Having been shortened; abbreviated.")
(gdbm-store-replace db "saused" "no definitions found.")
(gdbm-store-replace db "sincerely" "Not feigned or affected; genuine: sincere indignation.  Being without hypocrisy or pretense; true: a sincere friend.  Archaic. Pure; unadulterated.")
(gdbm-store-replace db "wee" "Very small; tiny. See Synonyms at small. Very early: the wee hours of the morning.  A short time; a little bit.")
(gdbm-store-replace db "funk" "Music. An earthy quality appreciated in music such as jazz or soul. Polish-born American biochemist whose research of deficiency diseases led to his discovery of vitamins, which he named in 1912. A state of cowardly fright; a panic. A cowardly, fearful person. To shrink from in fright or dread. To be afraid of.")
(gdbm-store-replace db "impugn" "no definitions found.")
(gdbm-store-replace db "knurl" "A knob, knot, or other small protuberance. One of a series of small ridges or grooves on the surface or edge of a metal object, such as a thumbscrew, to aid in gripping. To provide with knurls; mill.")
(gdbm-store-replace db "whore" "A prostitute. A person considered sexually promiscuous. A person considered as having compromised principles for personal gain. To associate or have sexual relations with prostitutes or a prostitute. To accept payment in exchange for sexual relations. To compromise one's principles for personal gain.")
(gdbm-store-replace db "fightp" "no definitions found.")
(gdbm-store-replace db "sortie" "An armed attack, especially one made from a place surrounded by enemy forces. A flight of a combat aircraft on a mission. To go on a sortie.")
(gdbm-store-replace db "honk" "The raucous, resonant sound characteristic of a wild goose.  A sound similar to a goose's honk: blew a loud honk on the bass saxophone.  To emit a honk. To cause (a horn) to produce a honk.")
(gdbm-store-replace db "trifecta" "A system of betting in which the bettor must pick the first three winners in the correct sequence. Also called triple.")
(gdbm-store-replace db "abrogate" "To abolish, do away with, or annul, especially by authority.")
(gdbm-store-replace db "scintillation" "The act of scintillating. A spark; a flash. Astronomy. Rapid variation in the light of a celestial body caused by turbulence in Earth's atmosphere; a twinkling. Physics. A flash of light produced in a phosphor by absorption of an ionizing particle or photon.")
(gdbm-store-replace db "somnolence" "A state of drowsiness; sleepiness.")
