(dynamic-load "gdbm.so")
(define db (gdbm-open "fight.db"))
(gdbm-store-replace db "nu-losses" "0")
(gdbm-store-replace db "benbot-alias" "anybot")
(gdbm-store-replace db "bisstardo-rank" "0")
(gdbm-store-replace db "sarahmay_-losses" "1")
(gdbm-store-replace db "echo23___-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "wuss_ian-o-rank" "0")
(gdbm-store-replace db "wuss_rthmchgs_HF-rank" "0")
(gdbm-store-replace db "nu123-alias" "eqnox")
(gdbm-store-replace db "poo-rank" "0")
(gdbm-store-replace db "ragecage-exp" "0")
(gdbm-store-replace db "kingBooze-gender" "M")
(gdbm-store-replace db "Testing123-time" "1057171824")
(gdbm-store-replace db "howie--hp" "54")
(gdbm-store-replace db "howie--death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "FightStress2-hp" "50")
(gdbm-store-replace db "extracheese-death-cry" "This must be Thursday.  I never could get the hang of Thursdays.")
(gdbm-store-replace db "extracheese-time" "1063981841")
(gdbm-store-replace db "bennid_-wins" "2")
(gdbm-store-replace db "amcrows-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "linguo-hp" "51")
(gdbm-store-replace db "ibot-losses" "252")
(gdbm-store-replace db "Bisstardo-losses" "1118")
(gdbm-store-replace db "JunkyWhiteAss-rank" "0")
(gdbm-store-replace db "Blah-exp" "1")
(gdbm-store-replace db "tempeqnox-rank" "0")
(gdbm-store-replace db "DudeGuy-death-cry" "something funny and ironic.")
(gdbm-store-replace db "tester-time" "1058443536")
(gdbm-store-replace db "memcpy-rank" "0")
(gdbm-store-replace db "ianbot_sucks-time" "1043771740")
(gdbm-store-replace db "_sarahmay-hp" "50")
(gdbm-store-replace db "niner-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "shizzlebot_-rank" "0")
(gdbm-store-replace db "extracheese-hp" "52")
(gdbm-store-replace db "TESTicles-losses" "22")
(gdbm-store-replace db "eqnoxiopener-time" "1055883937")
(gdbm-store-replace db "bartman-exp" "4")
(gdbm-store-replace db "EasyD_-wins" "0")
(gdbm-store-replace db "rthmchgs-wins" "1168")
(gdbm-store-replace db "amcrows-losses" "1")
(gdbm-store-replace db "Big_X-super-move" "~a squeezes out a Cleveland Steamer on ~a 's chest [~a]")
(gdbm-store-replace db "strego____-alias" "strego")
(gdbm-store-replace db "bennid-death-cry" "my enemy of my enemy, is my enemy")
(gdbm-store-replace db "cnae-rank" "0")
(gdbm-store-replace db "DSmooth_is_gay-exp" "0")
(gdbm-store-replace db "DudeGuy-losses" "176")
(gdbm-store-replace db "tester-n-exp" "0")
(gdbm-store-replace db "thegirl-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "drudge-alias" "eqnox")
(gdbm-store-replace db "ragecage-losses" "0")
(gdbm-store-replace db "benupstairs_-hp" "50")
(gdbm-store-replace db "sarahmay-time" "1060277743")
(gdbm-store-replace db "lamb-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "eqnox______-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "eqnox_away1-alias" "eqnox")
(gdbm-store-replace db "withbeck-rank" "0")
(gdbm-store-replace db "Sasquatch-super-move" "~a shoves his huge bigfoot cock 8¯¯¯¯¯¯¯D up ~a[~a]'s ass")
(gdbm-store-replace db "Sasquatch_-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "w00t-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "shizzlebot_-hp" "52")
(gdbm-store-replace db "strego_master_of_the_universe-exp" "0")
(gdbm-store-replace db "RageCage-hp" "65")
(gdbm-store-replace db "kingBooze-rank" "2")
(gdbm-store-replace db "Big_X__-hp" "51")
(gdbm-store-replace db "eqnox_lag-alias" "eqnox")
(gdbm-store-replace db "Blah-losses" "1")
(gdbm-store-replace db "FightStress2-exp" "123")
(gdbm-store-replace db "skemebot-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "echo23__-rank" "0")
(gdbm-store-replace db "lamb-hp" "51")
(gdbm-store-replace db "dudeguy-rank" "0")
(gdbm-store-replace db "oBisstard-time" "1064367840")
(gdbm-store-replace db "_eqnox-alias" "eqnox")
(gdbm-store-replace db "oBisstard-exp" "4")
(gdbm-store-replace db "jonb_-hp" "52")
(gdbm-store-replace db "BigBrother-rank" "0")
(gdbm-store-replace db "snoo-exp" "0")
(gdbm-store-replace db "bisstardo-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "jonb-time" "1058193932")
(gdbm-store-replace db "niner-alias" "bennid")
(gdbm-store-replace db "amcrows__-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "bisstardo_-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "bigeks-alias" "Big_X")
(gdbm-store-replace db "FightBot-rank" "0")
(gdbm-store-replace db "ackbarbot-alias" "anybot")
(gdbm-store-replace db "tester-n-losses" "0")
(gdbm-store-replace db "ianbot-alias" "anybot")
(gdbm-store-replace db "bisstardo_-gender" "M")
(gdbm-store-replace db "debo_-hp" "53")
(gdbm-store-replace db "bennid-hp" "52")
(gdbm-store-replace db "anybot-losses" "208")
(gdbm-store-replace db "Stalker-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "debo-time" "1064852133")
(gdbm-store-replace db "LostXanadu-hp" "57")
(gdbm-store-replace db "Greg-losses" "3")
(gdbm-store-replace db "strego-hp" "65")
(gdbm-store-replace db "strego-death-cry" "If you strike me down, I shall become more clever than you can possibly imagine!")
(gdbm-store-replace db "laptop-hp" "20")
(gdbm-store-replace db "laptop-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "FightStress1-losses" "1")
(gdbm-store-replace db "clesbug-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "wuss_rthmchgs_HF-wins" "0")
(gdbm-store-replace db "misyk-rank" "0")
(gdbm-store-replace db "bennid_-rank" "0")
(gdbm-store-replace db "SlowyC-rank" "0")
(gdbm-store-replace db "misyk-gender" "F")
(gdbm-store-replace db "jiffy-death-cry" "For King and Country!")
(gdbm-store-replace db "howie--losses" "9")
(gdbm-store-replace db "threepiobot-alias" "anybot")
(gdbm-store-replace db "wuss_Bisstardo-exp" "0")
(gdbm-store-replace db "too_many_nicks-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "CORNHOLIO-super-move" "~a whips some TP at ~a[~a]'s bunghole!")
(gdbm-store-replace db "FightStress1-wins" "2")
(gdbm-store-replace db "snoo-losses" "0")
(gdbm-store-replace db "aggresive-alias" "eqnox")
(gdbm-store-replace db "eqnoxiopener-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "JunkyWhiteAss-hp" "52")
(gdbm-store-replace db "JackBlack-exp" "36")
(gdbm-store-replace db "w00t-wins" "0")
(gdbm-store-replace db "howie--wins" "1")
(gdbm-store-replace db "eqnox-exp" "8")
(gdbm-store-replace db "howieeee-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "BossHogg-hp" "52")
(gdbm-store-replace db "linguo-wins" "0")
(gdbm-store-replace db "bennid-losses" "1982")
(gdbm-store-replace db "filter-exp" "0")
(gdbm-store-replace db "fighting_is_gay-losses" "0")
(gdbm-store-replace db "ThePurpleCow-wins" "1")
(gdbm-store-replace db "donald_-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "wpieqnox-alias" "eqnox")
(gdbm-store-replace db "poo-time" "1037825449")
(gdbm-store-replace db "nu-exp" "0")
(gdbm-store-replace db "kingBooze-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "anybot-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "F-Troop-exp" "190")
(gdbm-store-replace db "thehaus-losses" "25")
(gdbm-store-replace db "helper_monkey-wins" "1")
(gdbm-store-replace db "DarthBalls-death-cry" "Avenge me!!!!!")
(gdbm-store-replace db "hanbot-hp" "53")
(gdbm-store-replace db "bartman-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "Sedon-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "scriptless-exp" "0")
(gdbm-store-replace db "tester-n-wins" "0")
(gdbm-store-replace db "debo-rank" "7")
(gdbm-store-replace db "wuss_eqnox-rank" "0")
(gdbm-store-replace db "bennid-wins" "2019")
(gdbm-store-replace db "eqnox_lag-losses" "0")
(gdbm-store-replace db "howie--super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "niner-time" "1046874915")
(gdbm-store-replace db "donald_-losses" "9")
(gdbm-store-replace db "eqnox____-hp" "54")
(gdbm-store-replace db "_sarahmay-alias" "sarahmay")
(gdbm-store-replace db "jonb_-wins" "7")
(gdbm-store-replace db "DSmooth_is_gay-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "shizzlebot-hp" "52")
(gdbm-store-replace db "eqnox____-rank" "0")
(gdbm-store-replace db "emperorbot-alias" "anybot")
(gdbm-store-replace db "echo23_-wins" "2")
(gdbm-store-replace db "Big_X-time" "1064433262")
(gdbm-store-replace db "sedon-wins" "4")
(gdbm-store-replace db "f-troop-losses" "8")
(gdbm-store-replace db "Bisstardo -losses" "613")
(gdbm-store-replace db "thehaus-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "beawolf1-time" "1045492562")
(gdbm-store-replace db "lukebot-wins" "0")
(gdbm-store-replace db "howie_-losses" "0")
(gdbm-store-replace db "debo_-wins" "0")
(gdbm-store-replace db "obisstard-time" "1063401558")
(gdbm-store-replace db "LostXanadu-gender" "M")
(gdbm-store-replace db "fightstress2-losses" "0")
(gdbm-store-replace db "strego_IM-alias" "strego")
(gdbm-store-replace db "JackBlack-death-cry" "All we're asking you to do is to squeeze out a Cleveland Steamer right on my chest!")
(gdbm-store-replace db "strego-losses" "1008")
(gdbm-store-replace db "echo23___-hp" "50")
(gdbm-store-replace db "TESTicles-time" "1039027358")
(gdbm-store-replace db "obisstard-exp" "1")
(gdbm-store-replace db "CNAE-rank" "0")
(gdbm-store-replace db "homer-time" "1046195691")
(gdbm-store-replace db "wuss_ian-o-exp" "0")
(gdbm-store-replace db "downstairs-exp" "0")
(gdbm-store-replace db "rthmchgs-super-move" "~a gets out a laptop, goes to http://www.sassmaster.com/hotchicks, ~a[~a] is distracted and gets kicked in the eye.")
(gdbm-store-replace db "sass794-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "testing-exp" "0")
(gdbm-store-replace db "fightstress2-wins" "0")
(gdbm-store-replace db "ibot-wins" "100")
(gdbm-store-replace db "thegirl-hp" "50")
(gdbm-store-replace db "howieeee-rank" "0")
(gdbm-store-replace db "strego-wins" "931")
(gdbm-store-replace db "strego___-alias" "strego")
(gdbm-store-replace db "TESTicles-exp" "150")
(gdbm-store-replace db "knowbot-death-cry" "Schemebot is sooooooo much cooler than me. I suck!")
(gdbm-store-replace db "cnae-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "GoldHunter-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "laptop-wins" "0")
(gdbm-store-replace db "tarkinbot-alias" "anybot")
(gdbm-store-replace db "drudgebot-alias" "eqnox")
(gdbm-store-replace db "skemebot-hp" "53")
(gdbm-store-replace db "sass794-losses" "1")
(gdbm-store-replace db "shizzlebot-wins" "144")
(gdbm-store-replace db "Greg-wins" "0")
(gdbm-store-replace db "sarahmay-death-cry" "I'm leaving")
(gdbm-store-replace db "niner-exp" "14")
(gdbm-store-replace db "ThePurpleCow-hp" "51")
(gdbm-store-replace db "LostXanadu-death-cry" "I'm the chucklehead...")
(gdbm-store-replace db "DSmooth-death-cry" "Don't forget about Tenacious D...")
(gdbm-store-replace db "thehaus-time" "1048609513")
(gdbm-store-replace db "knowbot1-alias" "knowbot")
(gdbm-store-replace db "landobot-alias" "anybot")
(gdbm-store-replace db "knowbot-losses" "604")
(gdbm-store-replace db "molemark-alias" "strego")
(gdbm-store-replace db "nu-hp" "54")
(gdbm-store-replace db "yourself-rank" "0")
(gdbm-store-replace db "bisstardo_-time" "1064006255")
(gdbm-store-replace db "sarahmay_-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "Cracker-alias" "DudeGuy")
(gdbm-store-replace db "strego-super-move" "~a summons the power of SASS, and while ~a[~a] is distracted, hits him with a fish.")
(gdbm-store-replace db "scriptless-losses" "1")
(gdbm-store-replace db "Sasquatch-wins" "347")
(gdbm-store-replace db "wussy-losses" "1")
(gdbm-store-replace db "filter-rank" "0")
(gdbm-store-replace db "TheKid-alias" "eqnox")
(gdbm-store-replace db "amcrows-wins" "0")
(gdbm-store-replace db "JikoKanri-time" "1042040305")
(gdbm-store-replace db "withbeck-losses" "1")
(gdbm-store-replace db "DSmooth-losses" "2821")
(gdbm-store-replace db "poo-losses" "1")
(gdbm-store-replace db "DudeGuy-wins" "117")
(gdbm-store-replace db "donald_-time" "1060178460")
(gdbm-store-replace db "your_mother-rank" "0")
(gdbm-store-replace db "echo23_-rank" "0")
(gdbm-store-replace db "F-Troop-death-cry" "Ian owes me 8 dollars!!!")
(gdbm-store-replace db "cnae-exp" "0")
(gdbm-store-replace db "FightStress1-exp" "103")
(gdbm-store-replace db "SchemeFighter-exp" "0")
(gdbm-store-replace db "your_mother-hp" "52")
(gdbm-store-replace db "lukebot-rank" "0")
(gdbm-store-replace db "Bisstardo-death-cry" "I hate school and I hate all of you!  I'm never coming back here again! Never!!")
(gdbm-store-replace db "hanbot-wins" "1")
(gdbm-store-replace db "amcrows__-hp" "52")
(gdbm-store-replace db "bisstardo-wins" "4")
(gdbm-store-replace db "eqnox____-alias" "eqnox")
(gdbm-store-replace db "FightStress1-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "sarahmay-gender" "F")
(gdbm-store-replace db "DSmooth_is_gay-rank" "0")
(gdbm-store-replace db "anybot-exp" "26")
(gdbm-store-replace db "w00t-time" "1049746981")
(gdbm-store-replace db "leaving-rank" "0")
(gdbm-store-replace db "TESTicles-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "Big_X-death-cry" "There Can Be Only ONE.")
(gdbm-store-replace db "F-Troop-losses" "694")
(gdbm-store-replace db "misyk-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "scheme-fighter-last-loser" "debo")
(gdbm-store-replace db "wuss_ian-o-wins" "0")
(gdbm-store-replace db "_sarahmay-losses" "1")
(gdbm-store-replace db "BigBrother-exp" "0")
(gdbm-store-replace db "FightStress2-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "echo23-losses" "114")
(gdbm-store-replace db "donald-gender" "M")
(gdbm-store-replace db "donald___-time" "1058576330")
(gdbm-store-replace db "FightStress1-rank" "0")
(gdbm-store-replace db "howie--exp" "2")
(gdbm-store-replace db "downstairs-losses" "1")
(gdbm-store-replace db "tempeqnox-wins" "0")
(gdbm-store-replace db "wussy-rank" "0")
(gdbm-store-replace db "wuss_ian-o-losses" "0")
(gdbm-store-replace db "troop-losses" "0")
(gdbm-store-replace db "RageCage-exp" "246")
(gdbm-store-replace db "obisstard-rank" "0")
(gdbm-store-replace db "cnae-losses" "1")
(gdbm-store-replace db "sarahmay-rank" "12")
(gdbm-store-replace db "CORNHOLIO-wins" "1")
(gdbm-store-replace db "skemebot-rank" "0")
(gdbm-store-replace db "homer-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "JackBlack-super-move" "~a squeezes out a Cleveland Steamer on ~a[~a]'s chest!")
(gdbm-store-replace db "echo23___-alias" "echo23")
(gdbm-store-replace db "RageCage-losses" "396")
(gdbm-store-replace db "withbeck-wins" "0")
(gdbm-store-replace db "C0RNH0L1O-wins" "1")
(gdbm-store-replace db "knowbot-time" "1043701988")
(gdbm-store-replace db "ian-o-alias" "eqnox")
(gdbm-store-replace db "Stalker-wins" "0")
(gdbm-store-replace db "bennid-exp" "54")
(gdbm-store-replace db "schemebot-hp" "1025")
(gdbm-store-replace db "dudeguy-exp" "16")
(gdbm-store-replace db "thehaus_-hp" "54")
(gdbm-store-replace db "extracheese-super-move" "~a slashes ~a[~a] with a hockey stick!")
(gdbm-store-replace db "eqnox_lag-exp" "3")
(gdbm-store-replace db "clesbug-wins" "0")
(gdbm-store-replace db "kingBooze-wins" "63")
(gdbm-store-replace db "howie_-alias" "F-Troop")
(gdbm-store-replace db "amcrows-gender" "F")
(gdbm-store-replace db "DSmooth-time" "1064848636")
(gdbm-store-replace db "amcrows-rank" "0")
(gdbm-store-replace db "sasquatch-hp" "52")
(gdbm-store-replace db "snoo-wins" "0")
(gdbm-store-replace db "thehaus-hp" "51")
(gdbm-store-replace db "schemebot-rank" "1000")
(gdbm-store-replace db "echo23-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "DudeGuy-rank" "2")
(gdbm-store-replace db "DudeGuy-gender" "M")
(gdbm-store-replace db "jenny-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "biz-wins" "1")
(gdbm-store-replace db "fightstress2-exp" "0")
(gdbm-store-replace db "wuss_Bisstardo-rank" "0")
(gdbm-store-replace db "jiffy-hp" "66")
(gdbm-store-replace db "wuss_a_is_rthmchgs-wins" "0")
(gdbm-store-replace db "troop-rank" "0")
(gdbm-store-replace db "donald_-hp" "58")
(gdbm-store-replace db "shizzlebot-gender" "M")
(gdbm-store-replace db "FightBot-wins" "4")
(gdbm-store-replace db "JikoKanri-hp" "53")
(gdbm-store-replace db "beawolf1-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "bigeks-hp" "52")
(gdbm-store-replace db "RoShamBot-losses" "0")
(gdbm-store-replace db "eqnox______-losses" "2")
(gdbm-store-replace db "eqnox_away-rank" "0")
(gdbm-store-replace db "poo-exp" "1")
(gdbm-store-replace db "homer-losses" "1")
(gdbm-store-replace db "vaderbot-alias" "anybot")
(gdbm-store-replace db "F-Troop-time" "1064620026")
(gdbm-store-replace db "BigBrother-wins" "0")
(gdbm-store-replace db "f-troop-hp" "52")
(gdbm-store-replace db "wuss_eqnox-exp" "0")
(gdbm-store-replace db "ianbot_sucks-hp" "51")
(gdbm-store-replace db "JikoKanri-rank" "0")
(gdbm-store-replace db "strego_master_of_the_universe-rank" "0")
(gdbm-store-replace db "blah-hp" "51")
(gdbm-store-replace db "howie_-exp" "12")
(gdbm-store-replace db "wuss_a_is_rthmchgs-losses" "0")
(gdbm-store-replace db "CNAE-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "strego-exp" "195")
(gdbm-store-replace db "rthmchgs-hp" "57")
(gdbm-store-replace db "BigBrother-losses" "1")
(gdbm-store-replace db "fightstress2-rank" "0")
(gdbm-store-replace db "debo-exp" "17")
(gdbm-store-replace db "bartman-wins" "1")
(gdbm-store-replace db "Greg-time" "1064611129")
(gdbm-store-replace db "shizzlebot-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "anybot-rank" "2")
(gdbm-store-replace db "eqnox-losses" "912")
(gdbm-store-replace db "RageCage-wins" "433")
(gdbm-store-replace db "SlowyC-time" "1034966294")
(gdbm-store-replace db "GoldHunter-time" "1038948454")
(gdbm-store-replace db "donald___-hp" "54")
(gdbm-store-replace db "memcpy-losses" "1")
(gdbm-store-replace db "scriptless-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "CNAE-hp" "53")
(gdbm-store-replace db "donald-death-cry" "Disco Stu should have disco ducked!")
(gdbm-store-replace db "donald-hp" "54")
(gdbm-store-replace db "wuss_rthmchgs-exp" "0")
(gdbm-store-replace db "jenny-losses" "9")
(gdbm-store-replace db "TESTicles-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "LostXanadu-time" "1064621470")
(gdbm-store-replace db "howie--rank" "0")
(gdbm-store-replace db "Meggie-hp" "50")
(gdbm-store-replace db "Meggie-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "donald___-rank" "0")
(gdbm-store-replace db "Stalker-rank" "0")
(gdbm-store-replace db "eqnox____-losses" "0")
(gdbm-store-replace db "Clesbug-death-cry" "Ohhhh, the pain in the gladen...")
(gdbm-store-replace db "ibot-rank" "3")
(gdbm-store-replace db "misyk-time" "1032796532")
(gdbm-store-replace db "debo-losses" "428")
(gdbm-store-replace db "clesbug-rank" "0")
(gdbm-store-replace db "nunu-alias" "eqnox")
(gdbm-store-replace db "SchemeFighter-hp" "53")
(gdbm-store-replace db "BossHogg-losses" "2")
(gdbm-store-replace db "eqnox______-time" "1039026943")
(gdbm-store-replace db "eqnox______-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "DSmooth3650-alias" "DSmooth")
(gdbm-store-replace db "Blah-time" "1037825256")
(gdbm-store-replace db "sarahmay_-hp" "52")
(gdbm-store-replace db "knowbot-hp" "59")
(gdbm-store-replace db "Clesbug-losses" "3")
(gdbm-store-replace db "beawolf1-rank" "0")
(gdbm-store-replace db "sass794-wins" "0")
(gdbm-store-replace db "eqnox-rank" "23")
(gdbm-store-replace db "eqnoxiopener-losses" "2")
(gdbm-store-replace db "bennid_-alias" "bennid")
(gdbm-store-replace db "Deceiver-exp" "0")
(gdbm-store-replace db "jiffy-wins" "26")
(gdbm-store-replace db "fuckface-alias" "schemebot")
(gdbm-store-replace db "eqnox-gender" "M")
(gdbm-store-replace db "dudeguy-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "DudeHOME-alias" "DudeGuy")
(gdbm-store-replace db "oBisstard-wins" "2")
(gdbm-store-replace db "echo23___-losses" "1")
(gdbm-store-replace db "DSmooth-hp" "67")
(gdbm-store-replace db "wuss_eqnox-wins" "0")
(gdbm-store-replace db "ibot-gender" "M")
(gdbm-store-replace db "Greg-rank" "0")
(gdbm-store-replace db "wuss_rthmchgs-rank" "0")
(gdbm-store-replace db "scriptless-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "Bisstardo-hp" "53")
(gdbm-store-replace db "eqnoxiopener-alias" "eqnox")
(gdbm-store-replace db "wuss_eqnox-losses" "0")
(gdbm-store-replace db "DSmooth-wins" "3930")
(gdbm-store-replace db "bartman-rank" "0")
(gdbm-store-replace db "LostXanadu_-exp" "4")
(gdbm-store-replace db "Testing123-gender" "M")
(gdbm-store-replace db "howie_-rank" "0")
(gdbm-store-replace db "fighting_is_gay-alias" "eqnox")
(gdbm-store-replace db "echo23-exp" "11")
(gdbm-store-replace db "wuss_a_is_rthmchgs-rank" "0")
(gdbm-store-replace db "Deceiver-losses" "0")
(gdbm-store-replace db "too_many_nicks-hp" "51")
(gdbm-store-replace db "tester-n-hp" "50")
(gdbm-store-replace db "misyk-exp" "32")
(gdbm-store-replace db "FightStress1-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "strego-rank" "28")
(gdbm-store-replace db "eqnox_old-alias" "eqnox")
(gdbm-store-replace db "Blah-rank" "0")
(gdbm-store-replace db "F-Troop-wins" "441")
(gdbm-store-replace db "strego_-alias" "strego")
(gdbm-store-replace db "Trouble-losses" "1")
(gdbm-store-replace db "smay-alias" "sarahmay")
(gdbm-store-replace db "bennid_-losses" "0")
(gdbm-store-replace db "JackBlack-wins" "545")
(gdbm-store-replace db "SlowyC-losses" "16")
(gdbm-store-replace db "stroogins-alias" "strego")
(gdbm-store-replace db "bigeks-time" "1055343545")
(gdbm-store-replace db "pimpbot-time" "1033582362")
(gdbm-store-replace db "donald-wins" "256")
(gdbm-store-replace db "Sasquatch_-hp" "51")
(gdbm-store-replace db "echo23_-exp" "8")
(gdbm-store-replace db "Clesbug-time" "1034905745")
(gdbm-store-replace db "sass794-rank" "0")
(gdbm-store-replace db "Big_X_-alias" "Big_X")
(gdbm-store-replace db "FightBot-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "Meggie-wins" "0")
(gdbm-store-replace db "jonb_-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "amcrows__-losses" "1")
(gdbm-store-replace db "cnae-wins" "0")
(gdbm-store-replace db "lukebot-exp" "0")
(gdbm-store-replace db "Big_X-hp" "50")
(gdbm-store-replace db "RoShamBot-exp" "0")
(gdbm-store-replace db "DONOTFIGHTMEASSHOLE-alias" "eqnox")
(gdbm-store-replace db "jonb-super-move" "~a launches an ICBM at ~a[~a]")
(gdbm-store-replace db "_sarahmay-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "DSmooth_is_gay-hp" "51")
(gdbm-store-replace db "sedon-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "bisstardo_-hp" "52")
(gdbm-store-replace db "leaving-exp" "0")
(gdbm-store-replace db "debo_-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "niner-rank" "0")
(gdbm-store-replace db "Sasquatch-time" "1063905815")
(gdbm-store-replace db "niner-gender" "M")
(gdbm-store-replace db "LostXanadu_-rank" "0")
(gdbm-store-replace db "smay-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "snoo-rank" "0")
(gdbm-store-replace db "LostXandu-hp" "52")
(gdbm-store-replace db "debo-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "memcpy-alias" "strego")
(gdbm-store-replace db "strego_master_of_the_universe-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "homer-hp" "50")
(gdbm-store-replace db "eqnox__-alias" "eqnox")
(gdbm-store-replace db "RageCage-super-move" "~a unleashes a Rock Block of Bach onto ~a[~a]")
(gdbm-store-replace db "SlowyC-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "SirTestalot-exp" "0")
(gdbm-store-replace db "jiffy-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "wuss_rthmchgs-hp" "53")
(gdbm-store-replace db "w00t-exp" "0")
(gdbm-store-replace db "DSmoothXBox-alias" "DSmooth")
(gdbm-store-replace db "Sasquatch-exp" "17")
(gdbm-store-replace db "LostXandu-rank" "0")
(gdbm-store-replace db "bisstardo-time" "1046725849")
(gdbm-store-replace db "yourself-exp" "3")
(gdbm-store-replace db "oBisstard-losses" "0")
(gdbm-store-replace db "eqnox_away-exp" "2")
(gdbm-store-replace db "fightstress1-rank" "0")
(gdbm-store-replace db "LostXanadu_-hp" "54")
(gdbm-store-replace db "Trouble-time" "1038947324")
(gdbm-store-replace db "jonb_-losses" "9")
(gdbm-store-replace db "F-Troop-rank" "12")
(gdbm-store-replace db "F-Troop-gender" "M")
(gdbm-store-replace db "fighting_is_gay-hp" "50")
(gdbm-store-replace db "bennid_-time" "1038408936")
(gdbm-store-replace db "bisstardo-exp" "17")
(gdbm-store-replace db "helper_monkey-losses" "1")
(gdbm-store-replace db "memcpy-exp" "0")
(gdbm-store-replace db "echo23-rank" "1")
(gdbm-store-replace db "jenny-hp" "54")
(gdbm-store-replace db "sedon-losses" "4")
(gdbm-store-replace db "nu-alias" "eqnox")
(gdbm-store-replace db "TESTicles-wins" "2")
(gdbm-store-replace db "smay-exp" "0")
(gdbm-store-replace db "Big_X__-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "amcrows-exp" "0")
(gdbm-store-replace db "howie-alias" "F-Troop")
(gdbm-store-replace db "sasquatch-losses" "0")
(gdbm-store-replace db "echo23_-alias" "echo23")
(gdbm-store-replace db "eqnoxiopener-exp" "5")
(gdbm-store-replace db "eqnox_lag-hp" "50")
(gdbm-store-replace db "wuss_Bisstardo-hp" "51")
(gdbm-store-replace db "ibot-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "SchemeFighter-losses" "1")
(gdbm-store-replace db "lukebot-alias" "anybot")
(gdbm-store-replace db "DudeGuy-exp" "228")
(gdbm-store-replace db "donald__-exp" "2")
(gdbm-store-replace db "CORNHOLIO-time" "1035314522")
(gdbm-store-replace db "strego2-alias" "strego")
(gdbm-store-replace db "SirTestalot-losses" "1")
(gdbm-store-replace db "ibot-hp" "53")
(gdbm-store-replace db "tempeqnox-exp" "0")
(gdbm-store-replace db "EasyD_-hp" "53")
(gdbm-store-replace db "TheMonk-alias" "DSmooth")
(gdbm-store-replace db "Sasquatch-gender" "M")
(gdbm-store-replace db "Big_X-wins" "712")
(gdbm-store-replace db "EasyD_-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "FightStress2-wins" "5")
(gdbm-store-replace db "extracheese-exp" "36")
(gdbm-store-replace db "pimpbot-hp" "52")
(gdbm-store-replace db "scriptbot-hp" "52")
(gdbm-store-replace db "C0RNH0L1O-time" "1035316735")
(gdbm-store-replace db "jonb-wins" "137")
(gdbm-store-replace db "DarthBalls-hp" "51")
(gdbm-store-replace db "CORNHOLIO-exp" "7")
(gdbm-store-replace db "bennid-gender" "M")
(gdbm-store-replace db "shizzlebot_-exp" "0")
(gdbm-store-replace db "eqnoxiopener-rank" "0")
(gdbm-store-replace db "Clesbug-hp" "51")
(gdbm-store-replace db "echo23___-exp" "0")
(gdbm-store-replace db "debo_-losses" "3")
(gdbm-store-replace db "strego_master_of_the_universe-alias" "strego")
(gdbm-store-replace db "kingBooze-time" "1036702105")
(gdbm-store-replace db "echo23_-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "scriptbot-rank" "0")
(gdbm-store-replace db "DSmooth_is_gay-losses" "1")
(gdbm-store-replace db "smay-losses" "1")
(gdbm-store-replace db "Troopy-alias" "F-Troop")
(gdbm-store-replace db "JackBlack-losses" "616")
(gdbm-store-replace db "C0RNH0L1O-exp" "2")
(gdbm-store-replace db "extracheese-losses" "498")
(gdbm-store-replace db "testing-rank" "0")
(gdbm-store-replace db "lukebot-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "sedon-rank" "0")
(gdbm-store-replace db "homer-wins" "0")
(gdbm-store-replace db "bisstardo-gender" "M")
(gdbm-store-replace db "filter-losses" "0")
(gdbm-store-replace db "withbeck-hp" "52")
(gdbm-store-replace db "debo-wins" "234")
(gdbm-store-replace db "biz-exp" "5")
(gdbm-store-replace db "donald__-losses" "2")
(gdbm-store-replace db "TheMonk-death-cry" "I am better than my statistics say I am")
(gdbm-store-replace db "ibot-exp" "1")
(gdbm-store-replace db "obisstard-wins" "0")
(gdbm-store-replace db "eqnox_away-wins" "1")
(gdbm-store-replace db "skemebot-wins" "0")
(gdbm-store-replace db "wedgebot-alias" "anybot")
(gdbm-store-replace db "JunkyWhiteAss-exp" "0")
(gdbm-store-replace db "bisstardo_-wins" "0")
(gdbm-store-replace db "rthmchgs-losses" "949")
(gdbm-store-replace db "DSmooth_sub_master_of_the universe-alias" "strego_master_of_the_universe")
(gdbm-store-replace db "lukebot-losses" "1")
(gdbm-store-replace db "Greg-exp" "1")
(gdbm-store-replace db "Sasquatch-rank" "13")
(gdbm-store-replace db "eqnox_away-losses" "3")
(gdbm-store-replace db "Stalker-exp" "0")
(gdbm-store-replace db "Blah-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "cnae-time" "1038842865")
(gdbm-store-replace db "SirTestalot-time" "1038947187")
(gdbm-store-replace db "wussy-exp" "1")
(gdbm-store-replace db "dudeguy-wins" "3")
(gdbm-store-replace db "SirTestalot-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "strego-gender" "M")
(gdbm-store-replace db "benupstairs-alias" "bennid")
(gdbm-store-replace db "jenny-wins" "8")
(gdbm-store-replace db "echo23__-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "clesbug-exp" "0")
(gdbm-store-replace db "DarthBalls-wins" "0")
(gdbm-store-replace db "FightBot-hp" "51")
(gdbm-store-replace db "too_many_nicks-exp" "0")
(gdbm-store-replace db "strego_master_of_the_universe-time" "0")
(gdbm-store-replace db "downstairs-rank" "0")
(gdbm-store-replace db "Trouble-hp" "52")
(gdbm-store-replace db "GoldHunter-hp" "52")
(gdbm-store-replace db "SlowyC-exp" "82")
(gdbm-store-replace db "troop-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "snoogins-alias" "bennid")
(gdbm-store-replace db "misyk-death-cry" "ach...")
(gdbm-store-replace db "DarthBalls-losses" "1")
(gdbm-store-replace db "bennid_-hp" "54")
(gdbm-store-replace db "FightBot-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "BigBrother-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "lukebot-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "w00t-hp" "52")
(gdbm-store-replace db "knowbot-rank" "9")
(gdbm-store-replace db "knowbot-gender" "M")
(gdbm-store-replace db "rthmchgs_-alias" "rthmchgs")
(gdbm-store-replace db "Jedi---exp" "1")
(gdbm-store-replace db "donald__-wins" "1")
(gdbm-store-replace db "donald-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "hanbot-rank" "0")
(gdbm-store-replace db "obisstard-losses" "1")
(gdbm-store-replace db "eqnoxathome-losses" "2")
(gdbm-store-replace db "kingBooze-death-cry" "why do I bother")
(gdbm-store-replace db "DSmooth-rank" "127")
(gdbm-store-replace db "DSmooth-gender" "M")
(gdbm-store-replace db "sarahmay_-wins" "0")
(gdbm-store-replace db "DSmooth_is_gay-time" "1041874364")
(gdbm-store-replace db "Big_X__-losses" "0")
(gdbm-store-replace db "RageCage-death-cry" "Definitely Poop-smookey!")
(gdbm-store-replace db "scriptless-time" "1034955663")
(gdbm-store-replace db "JunkyWhiteAss-wins" "0")
(gdbm-store-replace db "_sarahmay-rank" "0")
(gdbm-store-replace db "thegirl-exp" "23")
(gdbm-store-replace db "eqnox____-time" "1061234511")
(gdbm-store-replace db "troop-alias" "F-Troop")
(gdbm-store-replace db "_echo23__-alias" "echo23")
(gdbm-store-replace db "Bisstardo-wins" "1105")
(gdbm-store-replace db "sarahmay-wins" "427")
(gdbm-store-replace db "misyk-losses" "9")
(gdbm-store-replace db "too_many_nicks-losses" "1")
(gdbm-store-replace db "schemebot-losses" "1")
(gdbm-store-replace db "shizzlebot_-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "FoundClit-alias" "LostXanadu")
(gdbm-store-replace db "eqnox____-exp" "1")
(gdbm-store-replace db "DSmooth_-alias" "DSmooth")
(gdbm-store-replace db "jiffy-exp" "164")
(gdbm-store-replace db "GoldHunter-losses" "1")
(gdbm-store-replace db "leaving-time" "1038949117")
(gdbm-store-replace db "LostXanadu-wins" "1063")
(gdbm-store-replace db "eqnox_away-hp" "52")
(gdbm-store-replace db "amcrows-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "FightStress2-losses" "1")
(gdbm-store-replace db "DudeGuy-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "beawolf1-exp" "0")
(gdbm-store-replace db "Sasquatch_-alias" "Sasquatch")
(gdbm-store-replace db "EasyD_-time" "1061618944")
(gdbm-store-replace db "eqnoxathome-hp" "53")
(gdbm-store-replace db "niner-wins" "2")
(gdbm-store-replace db "DSmooth__-alias" "DSmooth")
(gdbm-store-replace db "w00t-losses" "2")
(gdbm-store-replace db "LostXanadu-losses" "848")
(gdbm-store-replace db "nu1-alias" "eqnox")
(gdbm-store-replace db "wussy-time" "1041874711")
(gdbm-store-replace db "RageCage-gender" "M")
(gdbm-store-replace db "echo23-gender" "M")
(gdbm-store-replace db "JikoKanri-losses" "0")
(gdbm-store-replace db "sedon-hp" "50")
(gdbm-store-replace db "helper_monkey-alias" "anybot")
(gdbm-store-replace db "howie_-hp" "54")
(gdbm-store-replace db "eqnoxathome-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "eqnox-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "debo__-alias" "debo")
(gdbm-store-replace db "F-Troop_-alias" "F-Troop")
(gdbm-store-replace db "rthmchgs-exp" "79")
(gdbm-store-replace db "RoShamBot-hp" "53")
(gdbm-store-replace db "lamb-exp" "0")
(gdbm-store-replace db "jiffy_-hp" "51")
(gdbm-store-replace db "Greg-hp" "53")
(gdbm-store-replace db "Greg-death-cry" "Its not really me")
(gdbm-store-replace db "jonb_-rank" "0")
(gdbm-store-replace db "jenny-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "SirTestalot-rank" "0")
(gdbm-store-replace db "benupstairs_-losses" "6")
(gdbm-store-replace db "RoShamBot-rank" "0")
(gdbm-store-replace db "pimpbot-wins" "1")
(gdbm-store-replace db "beawolf1-losses" "2")
(gdbm-store-replace db "anybot-wins" "88")
(gdbm-store-replace db "extracheese-wins" "410")
(gdbm-store-replace db "Stalker-losses" "2")
(gdbm-store-replace db "bigeks-exp" "0")
(gdbm-store-replace db "RageCage-rank" "15")
(gdbm-store-replace db "ibot-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "debo_-rank" "0")
(gdbm-store-replace db "ragecage-wins" "0")
(gdbm-store-replace db "blah-time" "1039720008")
(gdbm-store-replace db "Big_X__-time" "1039895062")
(gdbm-store-replace db "clesbug-losses" "2")
(gdbm-store-replace db "ianbot_sucks-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "Jedi---rank" "0")
(gdbm-store-replace db "nofightEqnox-alias" "eqnox")
(gdbm-store-replace db "DudeGuy-time" "1061316109")
(gdbm-store-replace db "benupstairs_-wins" "1")
(gdbm-store-replace db "DSmooth_is_gay-wins" "0")
(gdbm-store-replace db "DDTS-alias" "LostXanadu")
(gdbm-store-replace db "_sarahmay-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "howieeee-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "troop-time" "1055602331")
(gdbm-store-replace db "donald___-losses" "1")
(gdbm-store-replace db "benupstairs_-alias" "bennid")
(gdbm-store-replace db "Sasquatch-hp" "52")
(gdbm-store-replace db "SirTestalot-hp" "52")
(gdbm-store-replace db "extracheese-rank" "13")
(gdbm-store-replace db "CNAE-time" "1038856567")
(gdbm-store-replace db "lamb-losses" "1")
(gdbm-store-replace db "echo23__-hp" "50")
(gdbm-store-replace db "LostXandu-wins" "0")
(gdbm-store-replace db "anybot-time" "1048276003")
(gdbm-store-replace db "BossHogg-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "bisstardo-hp" "54")
(gdbm-store-replace db "shizzlebot-exp" "42")
(gdbm-store-replace db "yourself-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "shizzlebot_-wins" "0")
(gdbm-store-replace db "donald-exp" "38")
(gdbm-store-replace db "echo23_-hp" "51")
(gdbm-store-replace db "your_mother-exp" "0")
(gdbm-store-replace db "Blah-hp" "54")
(gdbm-store-replace db "thegirl-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "howie--time" "1033487408")
(gdbm-store-replace db "Meggie-exp" "0")
(gdbm-store-replace db "lukebot-hp" "54")
(gdbm-store-replace db "nu-rank" "0")
(gdbm-store-replace db "bartman-losses" "3")
(gdbm-store-replace db "wuss_Bisstardo-losses" "0")
(gdbm-store-replace db "tempeqnox-hp" "50")
(gdbm-store-replace db "BigBrother-time" "1038932676")
(gdbm-store-replace db "leaving-hp" "50")
(gdbm-store-replace db "thehaus-exp" "33")
(gdbm-store-replace db "Trouble-wins" "0")
(gdbm-store-replace db "DarthBalls-alias" "LostXanadu")
(gdbm-store-replace db "amcrows__-exp" "0")
(gdbm-store-replace db "blah-rank" "0")
(gdbm-store-replace db "thegirl-losses" "2")
(gdbm-store-replace db "beawolf1-wins" "0")
(gdbm-store-replace db "eqnox_lag-wins" "1")
(gdbm-store-replace db "linguo-death-cry" "I'll just go back to schooling your bad grammar!!!")
(gdbm-store-replace db "Deceiver-hp" "53")
(gdbm-store-replace db "CORNHOLIO-hp" "51")
(gdbm-store-replace db "biz-hp" "51")
(gdbm-store-replace db "donald_-exp" "134")
(gdbm-store-replace db "bennid-time" "1064797246")
(gdbm-store-replace db "wussy-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "donald_-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "leaving-wins" "0")
(gdbm-store-replace db "echo23-hp" "50")
(gdbm-store-replace db "echo23-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "Stalker-time" "1045688485")
(gdbm-store-replace db "wuss_Bisstardo-wins" "0")
(gdbm-store-replace db "troop-exp" "1")
(gdbm-store-replace db "C0RNH0L1O-hp" "52")
(gdbm-store-replace db "rthmchgs-time" "1064802626")
(gdbm-store-replace db "howie_-wins" "2")
(gdbm-store-replace db "CORNHOLIO-rank" "0")
(gdbm-store-replace db "bartman-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "f-troop-exp" "7")
(gdbm-store-replace db "f-troop-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "clesbug-time" "1034310727")
(gdbm-store-replace db "echo23___-rank" "0")
(gdbm-store-replace db "FightStress1-hp" "50")
(gdbm-store-replace db "wuss_rthmchgs-losses" "0")
(gdbm-store-replace db "stregoDDR-alias" "strego")
(gdbm-store-replace db "memcpy-gender" "M")
(gdbm-store-replace db "kingBooze-hp" "50")
(gdbm-store-replace db "jiffy_-wins" "1")
(gdbm-store-replace db "scriptbot-wins" "1")
(gdbm-store-replace db "snoo-hp" "51")
(gdbm-store-replace db "LostXanadu_-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "KGFighter-alias" "RageCage")
(gdbm-store-replace db "bigecks-alias" "Big_X")
(gdbm-store-replace db "schemebot-time" "1059486979")
(gdbm-store-replace db "sarahmay-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "donald__-time" "1060365131")
(gdbm-store-replace db "bigeks-rank" "0")
(gdbm-store-replace db "eqnox-time" "1064710171")
(gdbm-store-replace db "EasyD_-losses" "2")
(gdbm-store-replace db "crewbitch-alias" "amcrows")
(gdbm-store-replace db "poo-wins" "0")
(gdbm-store-replace db "extracheese-gender" "M")
(gdbm-store-replace db "skemebot-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "your_mother-losses" "3")
(gdbm-store-replace db "amcrows-hp" "50")
(gdbm-store-replace db "DudeGuy-hp" "67")
(gdbm-store-replace db "jenny-time" "1033141848")
(gdbm-store-replace db "schemebot-exp" "1388")
(gdbm-store-replace db "helper_monkey-exp" "3")
(gdbm-store-replace db "shizzlebot-losses" "713")
(gdbm-store-replace db "Big_X-exp" "23")
(gdbm-store-replace db "ben-alias" "bennid")
(gdbm-store-replace db "misyk-hp" "52")
(gdbm-store-replace db "jiffy_-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "strego-time" "1064708899")
(gdbm-store-replace db "FightStress2-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "Big_X__-wins" "1")
(gdbm-store-replace db "sasquatch-exp" "0")
(gdbm-store-replace db "sass794-exp" "0")
(gdbm-store-replace db "bartman-time" "1037758562")
(gdbm-store-replace db "andy-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "donald-rank" "6")
(gdbm-store-replace db "Trouble-rank" "0")
(gdbm-store-replace db "FightStress2-rank" "0")
(gdbm-store-replace db "knowbot-exp" "112")
(gdbm-store-replace db "knowbot-super-move" "~a rubs Kiki's 2 clits on ~a[~a] for massive damage")
(gdbm-store-replace db "thegirl-time" "1039542386")
(gdbm-store-replace db "benupstairs_-exp" "9")
(gdbm-store-replace db "JikoKanri-exp" "9")
(gdbm-store-replace db "homer-exp" "0")
(gdbm-store-replace db "Meggie-rank" "0")
(gdbm-store-replace db "JackBlack-time" "1064508306")
(gdbm-store-replace db "helper_monkey-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "andy-hp" "54")
(gdbm-store-replace db "strego_master_of_the_universe-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "obisstard-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "Deceiver-rank" "0")
(gdbm-store-replace db "lagunox-alias" "eqnox")
(gdbm-store-replace db "linguo-losses" "3")
(gdbm-store-replace db "LostXandu-losses" "0")
(gdbm-store-replace db "benupstairs_-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "DSmooth-super-move" "~a unleashes the DSmooth Swear Storm and ~a's ears bleed[~a]")
(gdbm-store-replace db "jonb_-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "Sasquatch_-rank" "0")
(gdbm-store-replace db "howieeee-hp" "54")
(gdbm-store-replace db "wuss_a_is_rthmchgs-hp" "53")
(gdbm-store-replace db "nu12-alias" "eqnox")
(gdbm-store-replace db "ThePurpleCow-losses" "0")
(gdbm-store-replace db "eqnox_away-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "sedon-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "big_x-rank" "0")
(gdbm-store-replace db "thehaus-death-cry" "A plague on both your houses!!!")
(gdbm-store-replace db "LostXanadu-super-move" "~a transforms into Yoda and uses the force on ~a [~a]")
(gdbm-store-replace db "fightstress2-hp" "0")
(gdbm-store-replace db "biz-rank" "0")
(gdbm-store-replace db "SchemeFighter-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "helper_monkey-rank" "0")
(gdbm-store-replace db "memcpy-hp" "50")
(gdbm-store-replace db "benupstairs_-rank" "0")
(gdbm-store-replace db "donald___-exp" "0")
(gdbm-store-replace db "andy-exp" "0")
(gdbm-store-replace db "jenny-exp" "31")
(gdbm-store-replace db "Stalker-hp" "53")
(gdbm-store-replace db "jonb-rank" "4")
(gdbm-store-replace db "schemebot-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "memcpy-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "CORNHOLIO-alias" "bennid")
(gdbm-store-replace db "yourself-hp" "52")
(gdbm-store-replace db "debo_-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "echo23-wins" "35")
(gdbm-store-replace db "F-Troop-super-move" "~a drops some around the world and back sass on ~a[~a].")
(gdbm-store-replace db "oBisstard-hp" "52")
(gdbm-store-replace db "bisstardo_-rank" "0")
(gdbm-store-replace db "clesbug-hp" "52")
(gdbm-store-replace db "_sarahmay-wins" "0")
(gdbm-store-replace db "your_mother-time" "1064277595")
(gdbm-store-replace db "your_mother-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "f-troop-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "oBisstard-rank" "0")
(gdbm-store-replace db "DSmooth-exp" "182")
(gdbm-store-replace db "strego_master_of_the_universe-losses" "1")
(gdbm-store-replace db "sarahmay_-time" "1044311384")
(gdbm-store-replace db "sancho-alias" "LostXanadu")
(gdbm-store-replace db "Bisstardo -wins" "493")
(gdbm-store-replace db "jiffy-losses" "39")
(gdbm-store-replace db "misyk-wins" "5")
(gdbm-store-replace db "eqnox-death-cry" "You will pay....")
(gdbm-store-replace db "Big_X__-rank" "0")
(gdbm-store-replace db "wuss_rthmchgs_HF-hp" "53")
(gdbm-store-replace db "EasyD_-alias" "donald")
(gdbm-store-replace db "wuss_rthmchgs_HF-losses" "0")
(gdbm-store-replace db "scriptless-hp" "51")
(gdbm-store-replace db "jonb-gender" "M")
(gdbm-store-replace db "sarahmay_-exp" "0")
(gdbm-store-replace db "JackBlack-gender" "M")
(gdbm-store-replace db "testing-losses" "0")
(gdbm-store-replace db "donald__-hp" "53")
(gdbm-store-replace db "andy-losses" "1")
(gdbm-store-replace db "eqnoxatwork-alias" "eqnox")
(gdbm-store-replace db "scriptbot-losses" "0")
(gdbm-store-replace db "debo_-alias" "debo")
(gdbm-store-replace db "Bisstardo-time" "1064805450")
(gdbm-store-replace db "trooperbot-alias" "anybot")
(gdbm-store-replace db "sasquatch-rank" "0")
(gdbm-store-replace db "bennid-super-move" "~a shoots staples at ~a[~a] [[ [ [[ [[ [ [[ [[ [ [[[ [[ [[[[!")
(gdbm-store-replace db "debo-gender" "F")
(gdbm-store-replace db "donald__-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "lamb-wins" "0")
(gdbm-store-replace db "laptop-losses" "1")
(gdbm-store-replace db "passive-alias" "rthmchgs")
(gdbm-store-replace db "strego__-alias" "strego")
(gdbm-store-replace db "bartman-hp" "53")
(gdbm-store-replace db "EasyD_-exp" "1")
(gdbm-store-replace db "donald___-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "Bisstardo-exp" "6")
(gdbm-store-replace db "your_mother-wins" "0")
(gdbm-store-replace db "withbeck-exp" "0")
(gdbm-store-replace db "rthmchgs-death-cry" "I just pictured mark in tear-away pants.....")
(gdbm-store-replace db "jiffy-rank" "0")
(gdbm-store-replace db "jiffy_-exp" "5")
(gdbm-store-replace db "Sasquatch-losses" "494")
(gdbm-store-replace db "rthmchgs1-alias" "rthmchgs")
(gdbm-store-replace db "sickmark-alias" "strego")
(gdbm-store-replace db "fightstress1-losses" "0")
(gdbm-store-replace db "f_is_gay-alias" "eqnox")
(gdbm-store-replace db "jiffy-gender" "M")
(gdbm-store-replace db "DarthBalls-rank" "0")
(gdbm-store-replace db "sarahmay-hp" "50")
(gdbm-store-replace db "fighting_is_gay-exp" "0")
(gdbm-store-replace db "wuss_ian-o-hp" "50")
(gdbm-store-replace db "downstairs-hp" "53")
(gdbm-store-replace db "JackBlack-hp" "54")
(gdbm-store-replace db "thegirl-wins" "3")
(gdbm-store-replace db "RoShamBot-wins" "0")
(gdbm-store-replace db "JackBlack-rank" "16")
(gdbm-store-replace db "echo23__-exp" "0")
(gdbm-store-replace db "big_x__-alias" "Big_X")
(gdbm-store-replace db "cnae-hp" "51")
(gdbm-store-replace db "blah-exp" "12")
(gdbm-store-replace db "fightstress1-wins" "0")
(gdbm-store-replace db "fighting_is_gay-wins" "0")
(gdbm-store-replace db "bisstardo-losses" "5")
(gdbm-store-replace db "helper_monkey-hp" "52")
(gdbm-store-replace db "SlowyC-hp" "53")
(gdbm-store-replace db "SlowyC-death-cry" "Its just a flesh wound....")
(gdbm-store-replace db "donald__-gender" "M")
(gdbm-store-replace db "FightBot-exp" "12")
(gdbm-store-replace db "hanbot-losses" "0")
(gdbm-store-replace db "jonb_-time" "1035858323")
(gdbm-store-replace db "memcpy-wins" "0")
(gdbm-store-replace db "sass794-hp" "53")
(gdbm-store-replace db "schoogins-alias" "rthmchgs")
(gdbm-store-replace db "Bisstardo-gender" "M")
(gdbm-store-replace db "CNAE-exp" "0")
(gdbm-store-replace db "sedon-time" "1045229118")
(gdbm-store-replace db "Jedi---hp" "53")
(gdbm-store-replace db "eqnox___-alias" "eqnox")
(gdbm-store-replace db "schemebot-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "rthmchgs-gender" "M")
(gdbm-store-replace db "ianbot_sucks-losses" "1")
(gdbm-store-replace db "Jedi---death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "tempeqnox-losses" "0")
(gdbm-store-replace db "debo_-time" "1063152640")
(gdbm-store-replace db "wussy-hp" "51")
(gdbm-store-replace db "TESTicles-gender" "M")
(gdbm-store-replace db "donald__-rank" "0")
(gdbm-store-replace db "echo23__-losses" "5")
(gdbm-store-replace db "niner-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "eqnox____-wins" "1")
(gdbm-store-replace db "CORNHOLIO-losses" "1")
(gdbm-store-replace db "blah-losses" "0")
(gdbm-store-replace db "ragecage-hp" "54")
(gdbm-store-replace db "ianbot_sucks-wins" "0")
(gdbm-store-replace db "sarahmay_-rank" "0")
(gdbm-store-replace db "ThePurpleCow-exp" "2")
(gdbm-store-replace db "shizzlebot-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "FightBot-losses" "20")
(gdbm-store-replace db "DSmooth________________-alias" "DSmooth")
(gdbm-store-replace db "eqnoxiopener-wins" "1")
(gdbm-store-replace db "pimpbot-exp" "9")
(gdbm-store-replace db "GoldHunter-rank" "0")
(gdbm-store-replace db "obisstard-hp" "53")
(gdbm-store-replace db "rthmchgs-rank" "32")
(gdbm-store-replace db "LostXandu-exp" "0")
(gdbm-store-replace db "OK-PAT-alias" "rthmchgs")
(gdbm-store-replace db "ThePurpleCow-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "eqnox_away-time" "1033474581")
(gdbm-store-replace db "leiabot-alias" "anybot")
(gdbm-store-replace db "Clesbug-exp" "0")
(gdbm-store-replace db "Clesbug-super-move" "~a shrugs her shoulders and ~a[~a] falls asleep")
(gdbm-store-replace db "CNAE-losses" "1")
(gdbm-store-replace db "linguo-exp" "0")
(gdbm-store-replace db "echo23__-alias" "echo23")
(gdbm-store-replace db "kingBooze-losses" "150")
(gdbm-store-replace db "LostXanadu-rank" "31")
(gdbm-store-replace db "JunkyWhiteAss-losses" "0")
(gdbm-store-replace db "TESTicles-hp" "500")
(gdbm-store-replace db "Bisstardo-rank" "31")
(gdbm-store-replace db "nu-wins" "0")
(gdbm-store-replace db "dudeguy-losses" "1")
(gdbm-store-replace db "BigBrother-hp" "50")
(gdbm-store-replace db "eqnox______-exp" "1")
(gdbm-store-replace db "wuss_rthmchgs-wins" "0")
(gdbm-store-replace db "eqnoxathome-alias" "eqnox")
(gdbm-store-replace db "thegirl-rank" "0")
(gdbm-store-replace db "thegirl-gender" "M")
(gdbm-store-replace db "jonb-death-cry" "schemebot favors DSmooth!!!")
(gdbm-store-replace db "jonb_-exp" "22")
(gdbm-store-replace db "echo23___-wins" "0")
(gdbm-store-replace db "TESTicles-rank" "0")
(gdbm-store-replace db "withbeck-time" "1047325757")
(gdbm-store-replace db "ThePurpleCow-rank" "0")
(gdbm-store-replace db "troop-hp" "54")
(gdbm-store-replace db "F-Troop-hp" "63")
(gdbm-store-replace db "sedon-exp" "15")
(gdbm-store-replace db "benupstairs_-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "fightstress1-hp" "0")
(gdbm-store-replace db "niner-losses" "1")
(gdbm-store-replace db "Sasquatch_-exp" "0")
(gdbm-store-replace db "EasyD_-rank" "0")
(gdbm-store-replace db "debo-death-cry" "killing me will only make me sassier!")
(gdbm-store-replace db "debo_-exp" "0")
(gdbm-store-replace db "jonb-hp" "51")
(gdbm-store-replace db "SchemeFighter-time" "1035299218")
(gdbm-store-replace db "Big_X-losses" "794")
(gdbm-store-replace db "eqnoxiopener-gender" "M")
(gdbm-store-replace db "w00t-rank" "0")
(gdbm-store-replace db "derekisgay-alias" "eqnox")
(gdbm-store-replace db "Deceiver-alias" "eqnox")
(gdbm-store-replace db "echo23__-wins" "0")
(gdbm-store-replace db "yodabot-alias" "anybot")
(gdbm-store-replace db "fighting_is_gay-rank" "0")
(gdbm-store-replace db "scriptbot-time" "1034956557")
(gdbm-store-replace db "beawolf1-hp" "52")
(gdbm-store-replace db "strego_master_of_the_universe-hp" "51")
(gdbm-store-replace db "wuss_a_is_rthmchgs-exp" "0")
(gdbm-store-replace db "JBFighter-alias" "JackBlack")
(gdbm-store-replace db "bisstardo_-exp" "0")
(gdbm-store-replace db "debo-hp" "52")
(gdbm-store-replace db "Jedi---losses" "3")
(gdbm-store-replace db "LostXanadu_-losses" "2")
(gdbm-store-replace db "Trouble-exp" "1")
(gdbm-store-replace db "SlowyC-wins" "11")
(gdbm-store-replace db "thehaus-wins" "10")
(gdbm-store-replace db "wussy-wins" "0")
(gdbm-store-replace db "bigeks-death-cry" "Shizzle wit da Drizzle......")
(gdbm-store-replace db "bennid_-exp" "14")
(gdbm-store-replace db "scriptbot-exp" "5")
(gdbm-store-replace db "eqnox_away2-alias" "eqnox")
(gdbm-store-replace db "jonb-exp" "28")
(gdbm-store-replace db "testing-hp" "54")
(gdbm-store-replace db "donald_-wins" "14")
(gdbm-store-replace db "ragecage-rank" "0")
(gdbm-store-replace db "biz-losses" "0")
(gdbm-store-replace db "Jedi---wins" "0")
(gdbm-store-replace db "howieeee-exp" "11")
(gdbm-store-replace db "eqnoxiopener-hp" "54")
(gdbm-store-replace db "fightstress1-exp" "0")
(gdbm-store-replace db "donald-time" "1064852073")
(gdbm-store-replace db "filter-hp" "52")
(gdbm-store-replace db "laptop-exp" "0")
(gdbm-store-replace db "dudeguy-time" "1043261430")
(gdbm-store-replace db "Deceiver-wins" "0")
(gdbm-store-replace db "Big_X-rank" "26")
(gdbm-store-replace db "RageCage-time" "1064346760")
(gdbm-store-replace db "BossHogg-exp" "0")
(gdbm-store-replace db "testing-wins" "0")
(gdbm-store-replace db "Bisstardo-super-move" "~a rips off ~a's balls and feeds them to his mother [~a]")
(gdbm-store-replace db "f-troop-wins" "4")
(gdbm-store-replace db "eqnox______-rank" "0")
(gdbm-store-replace db "Big_X-gender" "M")
(gdbm-store-replace db "FightStress1-time" "1039732175")
(gdbm-store-replace db "wuss_eqnox-hp" "54")
(gdbm-store-replace db "JM_Away-alias" "DudeGuy")
(gdbm-store-replace db "lamb-rank" "0")
(gdbm-store-replace db "hanbot-alias" "anybot")
(gdbm-store-replace db "jonb-losses" "263")
(gdbm-store-replace db "Sasquatch_-wins" "0")
(gdbm-store-replace db "troop-wins" "1")
(gdbm-store-replace db "eqnox_-alias" "eqnox")
(gdbm-store-replace db "tester-n-rank" "0")
(gdbm-store-replace db "scheme-fighter-last-winner" "shizzlebot")
(gdbm-store-replace db "linguo-rank" "0")
(gdbm-store-replace db "anybot-gender" "M")
(gdbm-store-replace db "howieeee-losses" "2")
(gdbm-store-replace db "homer-rank" "0")
(gdbm-store-replace db "eqnox-hp" "52")
(gdbm-store-replace db "eqnox______-hp" "53")
(gdbm-store-replace db "Sasquatch_-losses" "1")
(gdbm-store-replace db "LostXanadu_-time" "1046804607")
(gdbm-store-replace db "ianbot_sucks-exp" "0")
(gdbm-store-replace db "LostXanadu_-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "Big_X__-exp" "3")
(gdbm-store-replace db "poo-hp" "51")
(gdbm-store-replace db "poo-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "your_mother-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "EasyD-alias" "donald")
(gdbm-store-replace db "bennid-rank" "62")
(gdbm-store-replace db "DarthBalls-exp" "0")
(gdbm-store-replace db "strego_master_of_the_universe-wins" "2")
(gdbm-store-replace db "hanbot-exp" "6")
(gdbm-store-replace db "eqnox_lag-rank" "0")
(gdbm-store-replace db "yourself-losses" "0")
(gdbm-store-replace db "bisstardo_-losses" "2")
(gdbm-store-replace db "howieeee-alias" "F-Troop")
(gdbm-store-replace db "thehaus-rank" "0")
(gdbm-store-replace db "downstairs-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "knowbot-wins" "319")
(gdbm-store-replace db "schemebot-wins" "55")
(gdbm-store-replace db "jenny-rank" "0")
(gdbm-store-replace db "_sarahmay-time" "1046532454")
(gdbm-store-replace db "tester-gender" "M")
(gdbm-store-replace db "bigeks-losses" "3")
(gdbm-store-replace db "jenny-gender" "F")
(gdbm-store-replace db "ianbot_sucks-rank" "0")
(gdbm-store-replace db "shizzlebot-rank" "4")
(gdbm-store-replace db "donald_-rank" "0")
(gdbm-store-replace db "sasquatch-wins" "0")
(gdbm-store-replace db "Sasquatch-death-cry" "Tell em it was a friend...")
(gdbm-store-replace db "_sarahmay-exp" "0")
(gdbm-store-replace db "sarahmay-exp" "0")
(gdbm-store-replace db "skemebot-exp" "0")
(gdbm-store-replace db "f-troop-rank" "0")
(gdbm-store-replace db "Trouble-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "bigeks-wins" "0")
(gdbm-store-replace db "wussy-super-move" "~a executes an indescribable super-move on ~a[~a].~%")
(gdbm-store-replace db "JikoKanri-wins" "1")
(gdbm-store-replace db "JikoKanri-alias" "Big_X")
(gdbm-store-replace db "bisstardo-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "kingBooze-exp" "20")
(gdbm-store-replace db "howieeee-wins" "2")
(gdbm-store-replace db "echo23_-losses" "4")
(gdbm-store-replace db "JacobMar1ey-alias" "DudeGuy")
(gdbm-store-replace db "leaving-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "[jonb]-alias" "jonb")
(gdbm-store-replace db "donald-losses" "272")
(gdbm-store-replace db "laptop-rank" "0")
(gdbm-store-replace db "dudeguy-hp" "53")
(gdbm-store-replace db "withbeck-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "blah-wins" "1")
(gdbm-store-replace db "eqnoxathome-exp" "0")
(gdbm-store-replace db "filter-wins" "0")
(gdbm-store-replace db "eqnox-wins" "780")
(gdbm-store-replace db "Meggie-losses" "2")
(gdbm-store-replace db "GoldHunter-exp" "0")
(gdbm-store-replace db "wuss_rthmchgs_HF-exp" "0")
(gdbm-store-replace db "leaving-losses" "1")
(gdbm-store-replace db "sarahmay-losses" "512")
(gdbm-store-replace db "yourself-wins" "1")
(gdbm-store-replace db "shizzlebot_-losses" "1")
(gdbm-store-replace db "niner-hp" "54")
(gdbm-store-replace db "donald___-wins" "0")
(gdbm-store-replace db "w00t-death-cry" "I am too lame for a death-cry")
(gdbm-store-replace db "skemebot-losses" "1")
(gdbm-store-replace db "CNAE-wins" "0")
(gdbm-store-replace db "LostXanadu-exp" "89")
(gdbm-store-replace db "anybot-hp" "51")
(gdbm-store-replace db "anybot-death-cry" "I really love the cock!")
(gdbm-store-replace db "LostXanadu_-wins" "1")
(gdbm-store-replace db "CORNHOLIO-death-cry" "Where I come from... we have no bunghole")
